### ISSUE TITLE
Unable to run the AppLocker Policy Converter tool

### ISSUE THREAD

**Issue by Harvester57** [MicrosoftDocs/WDAC-Toolkit#114]
Hi,

I tried to test the AppLocker policy converter tool recently uploaded here, and it seems I cannot make it work on my work computer.

First, I had to install the .NET Runtime 6.0.7, otherwise I got an error message while trying to launch the executable. Now that the runtime is installed, I get an error message about hostpolicy.dll:

```
Cannot use file stream for [path\AppLocker-Policy-Converter.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'path\AppLocker-Policy-Converter.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'path\AppLocker-Converter\AppLocker-Policy-Converter.runtimeconfig.json' file and specify the appropriate framework.
```

Is it expected, and do I need to install another dependency ?

**Comment by jgeurten** [comment]
Hi, 

I have fixed the issue by packaging the missing components. You should now be able to run the app if you download the .zip package from the releases section. Please let me know if you have feedback on the tool.
