### ISSUE TITLE
Allow-listing wildcard folder doesn't seem to work

### ISSUE THREAD

**Issue by Webstah83** [MicrosoftDocs/WDAC-Toolkit#116]
I have a rule that allows c:\program files\* and c:\program files (x86)\* since none of our end users have admin rights so the only way to install apps is through Company Portal, or pushed as required apps from Intune. One of the apps we're deploying has a plethora of DLLs that are in the C:\program files (x86)\(vendor)\(title) and subfolders of title. The app refuses to launch when installed as DLLs are being blocked (seeing the event log errors under CodeIntegrity). Specific allow-listing of a single DLL file *is* possible, but with over 50 DLL files supporting the app (and of course they're unsigned!) the folder allow-listing is preferable and needs to work.

**Comment by MrrWhoo** [comment]
Confirmed here, It appears when you try to use "Folder" rule it ends up creating a file rule, When you re open the XML config again you can see that the entries are now FileRules instead of FolderRules

**Comment by jgeurten** [comment]
@MrrWhoo all path rules (folder path and file path) are all created in WDAC as "FilePath" rules. The WDAC schema does not have an attribute specific for FolderPath. You can see the various attributes at "\Windows\schemas\CodeIntegrity\cipolicy.xsd" under the <xs:element name="Allow">, <xs:element name="Deny">  and <xs:element name="FileAttrib"> elements

**Comment by MrrWhoo** [comment]
Thx for clarification!

**Comment by jgeurten** [comment]
@Webstah83 can you please share the relevant xml for the path rules? Are you using multiple policies? If so, do all the policies have the allow path rules? Are there any competing deny rules that match those blocked DLLs?
