### ISSUE TITLE
Single policy format option does not actually create a valid single policy format policy

### ISSUE THREAD

**Issue by jsuther1974** [MicrosoftDocs/WDAC-Toolkit#117]
Complete new policy choosing legacy policy format. This should produce a policy with <PolicyTypeID> rather than <BasePolicyID>/<PolicyID> (or Base+PolicyIDs that match the legacy PolicyTypeID GUID. Deploying this policy to downlevel (pre-1903) clients will not work. @jgeurten

**Comment by jgeurten** [comment]
Root cause is that the templates are multiple policy format. If there are no custom rules generated, the multiple policy template is output
