### ISSUE TITLE
The WDAC Policy Wizard generates unusable binary output filenames by default in Policy Merger mode

### ISSUE THREAD

**Issue by wdormann** [MicrosoftDocs/WDAC-Toolkit#130]
I've been testing deploying a WDAC Policy using the wizard, in conjunction with the Microsoft-approved [Deploy WDAC policies using script](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/deployment/deploy-wdac-policies-with-script) technique.

According to the guidance, `# Policy binary files should be named as {GUID}.cip for multiple policy format files (where {GUID} = <PolicyId> from the Policy XML)`.  And WDAC Policy Wizard does indeed obey this guidance for when `Policy Editor` is used:
![wdac-wizard-editor](https://user-images.githubusercontent.com/14325582/190645482-a6d70416-cd92-446f-b528-903b8071404d.png)

**However**, when the `Policy Merger" part of the wizard is used, the output file name is something that is **not** compatible with "script" deployment of WDAC.  If the output binary file is not renamed, it will never be used by Windows. At least, when the WDAC policy is being deployed via the "script" method.
![Screen Shot 2022-09-15 at 3 40 23 PM](https://user-images.githubusercontent.com/14325582/190648226-9d4835a2-bb0d-4619-9f74-309bd5abd303.png)

If I simply take the wizard output and simply **rename** it, it is applied properly.
![Screen Shot 2022-09-15 at 5 51 49 PM](https://user-images.githubusercontent.com/14325582/190648396-5c374264-bdeb-47e9-862b-1588b220bb16.png)

- The WDAC Policy Wizard in "Policy Merger" mode is creating a policy file in "multiple policy" format
- "Multiple policy" format binary files **must** be named as `{GUID}.cip` for Windows to use them, otherwise they will **silently** fail

I've heard that other methods for deploying WDAC policies (e.g. Intune) may require that the binary policy have a `.bin` extension.  I have not tested this yet, but my expectations are:

- WDAC Policy Wizard should be consistent with output file naming.  I see no reason for "Policy Editor" to use a different file name structure than "Policy Merger".  Both output a similar-looking (in content) XMl file and a binary file.
- If the file **name** of the binary output file matters (e.g. depending on what technique is used to deploy WDAC), then it would be nice if the WDAC Policy Wizard would note this to help steer the user in the right direction.  e.g. on the last page that lists the output file names.
- If the binary policy file name is of the wrong format (and therefore will result in a non-working WDAC policy), it would be nice if there was some sort of feedback to the user that something is wrong.  Granted, in the "script" deployment of WDAC, the actual deployment is really just in the copying of the policy file to the destination.  However, if somebody is following the Microsoft documentation to a T, then they'd be running `RefreshPolicy.exe` at the end.  And it seems plausible that `RefreshPolicy.exe` should be able to notice that the binary policy file is incorrectly named.

**Comment by jgeurten** [comment]
Good find and report @wdormann. I have fixed the bug and will open a PR and update the Wizard today. 

Multi-policy format merged outputs will have the schema {GUID}.cip, whereas the single policy formats will be built as SiPolicy.p7b. 

The reason RefreshPolicy.exe is reporting success is that it recurses through the list of policies in the CodeIntegrity Active directory and attempts to refresh each one. It does not report back the status of each individual policy refresh, just whether it was able to trigger refresh on the folder.
