### ISSUE TITLE
WDAC Wizard is Not creating policies when adding Publisher in allow list

### ISSUE THREAD

**Issue by KitCat36** [MicrosoftDocs/WDAC-Toolkit#133]
When I add an app's issuing CA and publisher to allow list, rule type publisher, WDAC Wizard fails to generate policy.

when I add a publisher to allow list, then I click on "create rule", WDAC Wizard says successfully created rule in its GUI but when I go to the actual folder output, no policy is created.

![image](https://user-images.githubusercontent.com/72892766/190896792-e53a040b-559f-415a-af87-9b60c4c7a5a1.png)

been trying it lots of times and after 10 tries, it still fails to do it. I'm using latest version of Windows 11.

![image](https://user-images.githubusercontent.com/72892766/190896075-611c1dcc-e53b-4c3a-b1ff-eb20ab5cfcd5.png)

![image](https://user-images.githubusercontent.com/72892766/190896562-df1099db-98c5-4f01-a9a8-4751c0409c41.png)

the successful page in WDAC Wizard's GUI.
when I click on the files in there to open, nothing happens, because they don't exist.

this happens whether I'm creating new policy from scratch, editing a current policy or creating a supplement policy.

here is the rest of the options I use 

![image](https://user-images.githubusercontent.com/72892766/190896753-09d5b845-322d-4ae2-aae3-e0804dc7ac50.png)
![image](https://user-images.githubusercontent.com/72892766/190896764-00e973b5-4e9f-4343-951f-0f667f02417b.png)

I tried everything I could think of to solve it, including restarting my system many times, reinstalling WDAC Wizard, resetting and refreshing WDAC Wizard app from Windows apps settings.

**Comment by jgeurten** [comment]
Can you share the log file of this session? It is stored in the AppData temp folder: ""C:\Users\<username>\AppData\Local\Temp\WDACWizard\Temp\<datetime>\Log_<datetime>.txt"

**Comment by jgeurten** [comment]
Good to hear the problem stopped happening. If you are able to reproduce the issue, we can re-open this issue. The Share logs anonymizes the user details so its not easy to locate which is yours.
