### ISSUE TITLE
Bug: WDAC Wizard doesn't disable User Mode Code Integrity

### ISSUE THREAD

**Issue by KitCat36** [MicrosoftDocs/WDAC-Toolkit#134]
Even when I turn off the toggle in WDAC Wizard like this:

![image](https://user-images.githubusercontent.com/72892766/190922832-f43a59d5-4b3c-421c-a1ae-5972cb786ee8.png)

after generating the policy file and opening the XML file, I see this:

![image](https://user-images.githubusercontent.com/72892766/190922934-48a68b47-4c03-4c9b-8d18-52435a9cf614.png)

So I have to manually delete this part 

```
<Rule>
<Option>Enabled:UMCI</Option>
</Rule>
```

from the generated XML policy file, in order to actually disable the User Mode Conde Integrity.

WDAC Wizard app version 1.7.0.0.22
Windows 11

**Comment by jgeurten** [comment]
Fixed in #118. Aiming to push an update this week which will contain the fix to this issue, plus many more features.
