### ISSUE TITLE
When I add a folder path of an installed program in Program files to the allow list of WDAC, it still gets blocked

### ISSUE THREAD

**Issue by KitCat36** [MicrosoftDocs/WDAC-Toolkit#135]
I added the installed path of a program to the allow list like this in WDAC Wizard:

![image](https://user-images.githubusercontent.com/72892766/190923359-0fe5e53e-2a56-4052-a19a-5679bef9877e.png)

but WDAC policy still blocks the executables and DLLs in that folder.

**Comment by jgeurten** [comment]
Did you try adding a wildcard to the end of the path? i.e. "C:\Program Files\MyProgram*" or "C:\Program Files\MyProgram\*"

**Comment by jgeurten** [comment]
Sorry, md typo.. Edited the paths above

**Comment by jgeurten** [comment]
more info on path rules in WDAC - https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#more-information-about-filepath-rules
