### ISSUE TITLE
Supplemental Policy Rules page is confusing

### ISSUE THREAD

**Issue by jsuther1974** [MicrosoftDocs/WDAC-Toolkit#137]
Create a new supplemental policy, proceed to the Policy Rules page of the wizard. These things look "wrong" to me:

1. There are a bunch of options already turned on (including options that are not configurable in a supplemental policy), where do these values come from? Is it the Base that was chosen? Or is it the supplemental template that the wizard uses?
2. Audit mode should not be configurable, but it allows you to toggle it
3. The options that are editable don't match the ones that are documented as configurable in a Supplemental. In fairness, other than audit mode, the ones you allow to be set are the only ones that are useful, but due to #1 and #2, I'm left confused overall https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#table-1-windows-defender-application-control-policy---policy-rule-options

**Comment by jgeurten** [comment]
1. The state is inherited from the base. When you hover over the label of an unsupported supp rule the Wizard shows this message currently 

![image](https://user-images.githubusercontent.com/23045608/193332022-7a329cb9-912a-469d-b99f-08b8b954b84e.png)

2. This is a bug. will fix
3. I don't support modifying rules 5 or 7. At the time of development, EV signers was supported but it might be worth removing now too
