### ISSUE TITLE
Can't update policy after I've deleted rules

### ISSUE THREAD

**Issue by SebMcCayen** [MicrosoftDocs/WDAC-Toolkit#157]
I have a Supplemental policy that I can't delete any rules from, because each time I try to save my policy nothing is created.
There is no problem adding new rules and saving the policy.

Have attached the log from my latest attempt:

[Log_2022-10-20_T06-06-50.txt](https://github.com/MicrosoftDocs/WDAC-Toolkit/files/9826888/Log_2022-10-20_T06-06-50.txt)

**Comment by jgeurten** [comment]
Was there at a time a rule with the ID=ID_ALLOW_A_1_0_1_0_0_0_0_0_0_0_0_0_0" ? The log shows that the xml is malformed since its missing this rule. It presumably exists in one of the signing scenarios but not in the FileRules section

**Comment by SebMcCayen** [comment]
> Was there at a time a rule with the ID=ID_ALLOW_A_1_0_1_0_0_0_0_0_0_0_0_0_0" ? The log shows that the xml is malformed since its missing this rule. It presumably exists in one of the signing scenarios but not in the FileRules section

Just had a look and it do exist in the FileRules and FileRulesRef-part of the file. Anything else that I can check?

**Comment by jgeurten** [comment]
Can you try running convertfrom-cipolicy <path_to xml> "./test.bin" and see what the output is?
