### ISSUE TITLE
Missing rules when merging policies

### ISSUE THREAD

**Issue by robdwhitehead** [MicrosoftDocs/WDAC-Toolkit#164]
Hi folks

Version: WDAC Toolkit version 1.7.0.0.22
OS: Windows 10 21H2 (OS Build 19044.2130)

I've noticed an issue with the WDAC Toolkit when merging multiple policies.  In my case, these were multiple Supplemental app XML's I'd generated as whitelists for specific apps I wanted to allow in Enforced Mode.   I generated a what I call Template XML that was a vanilla Supplemental policy tied to my Baseline policy (which was the Microsoft AllowMicrosoft template) - all fine there.  I then merge this XML with several of my whitelisted app XML's to make a single Supplemental policy, which is then deployed with the Baseline policy, both in Enforced Mode.  I compared the contents of one of the apps (Barco ClickShare Extension Pack) and it contained around 10 rules that were included in the source XML but once merged, lost around 10 lines worth of rules.  One of the files d3dcompiler_47.dll was even missing from the merged XML - probably more but this is just one I searched for as a test and picked up on immediately.  Is this a bug?  My primary rule level is FilePublisher with a fallback rule level of FilePath.  It can't be that the DLL is used in other apps and omitted as I am using a publisher primary rule level and so I'd expect these files to be fairly unique and signed to the developers within the apps they contain?

Any advice is appreciated.  For now, I can't really trust this tool to merge multiple policies and so I've had to revert back to PowerShell to merge where the GUI would be a little quicker.

Thanks

**Comment by jgeurten** [comment]
Hi @robdwhitehead, are you able to share the policies with me? You can email them to Jordan.Geurten@microsoft.com so I can investigate more. 

The Wizard simply calls the PowerShell merge-cipolicy command so if anything, there may be a bug with the Powershell cmd
