### ISSUE TITLE
Microsoft recommended rules are missing?

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/WDAC-Toolkit#17]
Are these recommendations missing from the templates?

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules

**Comment by jgeurten** [comment]
Hi @rafalfitt, this is a good feature request. I am going to add this to my iteration tracking process. Good suggestion!

Thanks!
