### ISSUE TITLE
[Bug] Multi-selecting packaged apps adds only a single rule

### ISSUE THREAD

**Issue by hj-collab** [MicrosoftDocs/WDAC-Toolkit#173]
Hi,

Multi-select for packaged app only adds one app to the rule. Regression? https://github.com/MicrosoftDocs/WDAC-Toolkit/pull/49

**Comment by jgeurten** [comment]
Hi @hj-collab, you can multi-select in the packaged app rules config panel - 

![image](https://user-images.githubusercontent.com/23045608/207409133-1a15295f-300d-416f-add1-26efe29a90de.png)

Are you indicating you are not seeing all of your PFN rules in the policy?

**Comment by jgeurten** [comment]
@hj-collab I see what you are seeing. This is a bug. Thanks for reporting this!
