### ISSUE TITLE
Does not work with add-package in Azure Stack HCI

### ISSUE THREAD

**Issue by lreevesazure** [MicrosoftDocs/WDAC-Toolkit#176]
Would be helpful with Azure Stack HCI Add to one node and set for cluster. - Error is Class not registered- after adding the MXIX tools that did install ok. [Releases · microsoft/msix-packaging (github.com)](https://github.com/microsoft/msix-packaging/releases)
Even windows 2019 says the OS is not right - Could the tool be updated?

**Comment by jgeurten** [comment]
Hi @lreevesazure do you have more info on this issue? I don't understand the problem

**Comment by jgeurten** [comment]
Since the app is a Windows Form application, there will not be any way to interface with the app on Azure Stack HCI. Closing this issue
