### ISSUE TITLE
Can't create custom rule from ECC-signed file

### ISSUE THREAD

**Issue by PanAlexandr** [MicrosoftDocs/WDAC-Toolkit#181]
Hello,

I use WDAC Wizard 2.1.0.1.22 and when I try to add custome rule:
1. Policy creator - Single policy format - Default Windows Mode 
2. Default Configure Policy Template 
3. Add Custome Rule
![rule](https://user-images.githubusercontent.com/121166051/208889544-9b35f43c-cdcd-40b2-8b6f-b419a8d69187.jpg)
4. Wizard generate XML-file but it doesn't include rule wich I try to add in step 3.

**Comment by jgeurten** [comment]
Can you share the zipped exe and the log file generated from this session? It would be stored on disk as %AppDataLocal%\Temp\WDACWizard\Temp 

I was able to create a signer rule for an older version of this file (1.10.2.297)

    <Signer Name="DigiCert EV Code Signing CA (SHA2)" ID="ID_SIGNER_S_1_0_0">
      <CertRoot Type="TBS" Value="EEC58131DC11CD7F512501B15FDBC6074C603B68CA91F7162D5A042054EDB0CF" />
      <CertPublisher Value="KnowBe4 Inc." />
    </Signer>

**Comment by PanAlexandr** [comment]
@jgeurten Thank you for support!
Here the zipped exe and logs
[PhishAlertButtonSetup.zip](https://github.com/MicrosoftDocs/WDAC-Toolkit/files/10284613/PhishAlertButtonSetup.zip)
Old version works fine but KnowBe4 update it and we didn't have intermidiate certificate which issued KnowBe4's certificate in the "Intermediate CA" store and get error "Issuing CA" was N\A (like that)
![rule1](https://user-images.githubusercontent.com/121166051/209080346-56e6f54a-45e7-4de2-b7ae-7f9eec1176d9.jpg)

When we added certificate "DigiCert Global G3 Code Signing ECC SHA384 2021 CA1" to "Intermediate CA" store (for user and for local computer) the issue has gone but WDAC wizard doesn't add the rule to policy XML-file.
Thank you in advance!

**Comment by jgeurten** [comment]
@PanAlexandr I have diagnosed the issue as a bug in the underlying PowerShell module (New-CIPolicyRule -Level Publisher -DriverFilePath <Path to exe>). I will not be able to fix this in the Wizard until the PowerShell bug is fixed. The bug has been filed on the Microsoft team. 

Thanks for bringing this to my attention.

**Comment by PanAlexandr** [comment]
@jgeurten Thank you for support! So, we can only wait for fixes in the PowerShell module. For my part, can I somehow speed up this process?
Thank you in advance!

**Comment by PanAlexandr** [comment]
@jgeurten Maybe you know some workaround how we can add such publisher to WDAC-policy?

**Comment by jgeurten** [comment]
@PanAlexandr I just learned it's actually a limitation of WDAC. WDAC does not support creating rules off ECC certificates and policies cannot be signed with ECC certificates.
