### ISSUE TITLE
Not able to update sysinternals microsoft store app with WDAC enabled

### ISSUE THREAD

**Issue by hj-collab** [MicrosoftDocs/WDAC-Toolkit#188]
Hi,

I have a WDAC policy which have sysinternals microsoft store app whitelisted. I am not able to update the app with WDAC enabled. Other whitelisted apps updates fine. 

![image](https://user-images.githubusercontent.com/101234934/214771708-68752568-f81a-45e0-a1af-b5589944abad.png)

I wonder why is this happening.

**Comment by jgeurten** [comment]
Hi, this is not a WDAC error message. This appears to be an Appx stack error

**Comment by milldogtjm** [comment]
Have you tried restoring the store or trying the uninstall and reintall app fix?
