### ISSUE TITLE
EventLogPolicy file is not saved to the file system when created

### ISSUE THREAD

**Issue by AndreasStenhall** [MicrosoftDocs/WDAC-Toolkit#208]
Go to Policy Editor > Convert Event Log to WDAC Policy and choose Parse MDE Advanced Hunting Events to Policy and then browse to and select a CSV file, then click Next, Next and watch it says "FInished creating WDAC Policy". However, no file has been created in the location that it says: C:\Users\<username>\OneDrive - Company\Dokument\EventLogPolicy_2023-02-17T15-18-35.xml
Tried on multiple devices in different organizations. Using OneDrive Known Folder Move to redirect Documents folder. Plus could be a localization issue, i.e. Dokument/Documents.

**Comment by jgeurten** [comment]
Hi @AndreasStenhall, 

The Wizard uses the .NET Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) so I don't suspect it's a file system issue. Rather, I think the wizard is failing to convert one or some of your rules. Can you share a subset of your rules (CSV files) with me from which you're trying to create rules?

**Comment by jgeurten** [comment]
After reviewing the data in the CSV, it's likely an issue with the save file location. All the events in the MDE CSV could be parsed correctly.
