### ISSUE TITLE
WDAC Policy Wizard isn't creating supplementary cip file

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/WDAC-Toolkit#211]
![image](https://user-images.githubusercontent.com/118815227/219890176-a941817e-5827-46a5-969e-86cda629967e.png)

The output shows there are 2 files, `.xml` policy file and `.cip` binary file, but as you can see in the output folder, there is only `.xml` policy file.

also, when I click on the blue file links on the app, they both open the same `.xml` file.

![image](https://user-images.githubusercontent.com/118815227/219890682-008cba0b-85be-48fd-9d2f-6d66afcead86.png)

This must be related to [this issue](https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/210) because when I use PowerShell to create `.cip` file from it, I get the same error.

Windows 11 insider dev build 25300
WDAC Policy Wizard Version 2.2.0.0

**Comment by jgeurten** [comment]
Yes, related to issue #210. Although, the Wizard should show when it failed to create the .cip file so I should fix this
