### ISSUE TITLE
WDAC Wizard not allowing changing a valid supplementary policy rule option in editing mode

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/WDAC-Toolkit#215]
[According to this official document](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create), `6 Enabled:Unsigned System Integrity Policy (Default)` is a valid policy rule option for a supplementary policy, but when I try to edit a supplementary policy using WDAC Policy Wizard, it doesn't let me modify that option.

![image](https://user-images.githubusercontent.com/118815227/221190927-4d48211b-eb09-4d14-9ad0-1af748123296.png)

**Comment by jgeurten** [comment]
This appears to be an issue with the documentation. Unsigned System Integrity Policy is inherited from the base and is not a valid supplemental policy. I will file a bug and update the official docs. 

Sorry for the confusion.

**Comment by HotCakeX** [comment]
@jgeurten Thank you!
