### ISSUE TITLE
Why is the WDAC Wizard failing to create supplemental policy by scanning a folder?

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/WDAC-Toolkit#218]
Recording everything in a short video to show it from start to end so there are no missing details:

https://1drv.ms/v/s!AtCaUNAJbbvIhtIVBObAKx7uSoZ5lg?e=QMDMRu

it's easily reproducible, I'm not doing anything out of the ordinary, no special use case, no specific user configuration applied to the OS. Just grabbed the latest official Windows 11 ISO from Microsoft website, created a Hyper-V with it, fully updated the OS and then recording this video.

I can successfully do exactly the same thing that WDAC wizard is failing at, using this PowerShell command:

```PowerShell
New-CIPolicy -FilePath .\Policy_LeafCertificate_FallBack_SignedVersion_FileName_FilePublisher_Hash.xml -ScanPath 'C:\Folder' -Level LeafCertificate -Fallback SignedVersion, FileName, FilePublisher, Hash -UserPEs -MultiplePolicyFormat -UserWriteablePaths
```

<br>

It doesn't matter whether I set the rule scope to usermode rule or kernel rule, it still gives me an empty policy.

**Comment by jgeurten** [comment]
Thanks for another report, @HotCakeX. I root caused the bug to this line: https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/main/WDAC-Policy-Wizard/app/src/MainForm.cs#L1426 which causes the final merge command to fail in the case of supplemental policies. 

As a temp workaround, your policy will have been created in the %AppDataLocal%\Temp\WDACWizard\Temp\<>\policy_0.xml. You will need to add <Rules> back to the policy

**Comment by HotCakeX** [comment]
@jgeurten  Anytime. Glad to know that,

Thank you, I just tried and found the policy in this folder `C:\Users\Admin\AppData\Local\Temp\WDACWizard\Temp\2023-02-27T05-47-54`
