### ISSUE TITLE
[Bug] Whitelisted programs are not been allowed to run

### ISSUE THREAD

**Issue by dennyamarojr** [MicrosoftDocs/WDAC-Toolkit#228]
Hi WDAC team,

Today I'm here to report an issue that I have been facing today, I try a lot ways but unfortunately I become with no result that I expected.

1 - I start to re-create my WDAC template and I start with a template with AllowMicrosoftMode
![image](https://user-images.githubusercontent.com/36896116/229261741-dd8b06a6-e909-4994-94d6-fd0962370f9f.png)

2- The policy rules is: 
![image](https://user-images.githubusercontent.com/36896116/229261755-a9ad0b92-f9be-4462-b679-880ecb5e4b2d.png)

3 - I merge the Recommended User Mode Block Rules and Recommended Kernel Block Rules and them create the template.
After that, I backup and them re-open in WDAC Policy Wizard to start whitelisting the programs I want.

4 - I whitelist Brave browser (Stable version and Nightly build), Google Chrome, KeepassXC, SumatraPDF and other programs that I have here. But when I go to whitelist Stremio, Open Video downloader, Mixxx the programs is not opening. Also the spotify with SpotX is not being opened.

- Here's the source for the programs:
  - Stremio: https://www.stremio.com/
  - Open Video Downloader: https://github.com/StefanLobbenmeier/youtube-dl-gui
  - Mixxx: https://github.com/mixxxdj/mixxx
  - SpotX: https://github.com/amd64fox/SpotX

And here's the things I try:

1 - Whitelist the executable files (Publisher) successfully create the rules for Stremio,Mixx, Spotify. Unfortunately for Open Video Downloader I had to create by file path.
2 - For SpotX, I whitelist the scripts inside the cache folder (hide_window.vbs, cache_spotify.ps1 and run_ps.bat)

**Obs:**  I didn't restart the computer after create the rules, but I test with a template using other template and I got the same results, where I restart the computer and the programs still been blocked even whitelist by Publisher, file path or folder path.

The template I tested previously was using this one here available in this project:
https://github.com/HotCakeX/Harden-Windows-Security

I generate the template and them edit with WDAC Policy Wizard and them edit to modify HVCI to strict mode and the result is Stremio, Mixx, Open Video Downloader and Spotify not opening. I was thinking that is the HVCI in strict mode but is not.

And for the final notes, I even allow brave,spotify,stremio for usermode and kernel mode, and didn't get any successfully result.

**Comment by HotCakeX** [comment]
Hi,
* "Treat revoked as unsigned" rule option has no use for you if you aren't using ISG (Intelligent Security Graph).

* If you are using latest Windows 11 22H2 version and also using Memory Integrity in Microsoft Defender, then you don't need to merge Microsoft recommended block rules as they're already deployed and enforced automatically.

* For better manageability and maintenance, I suggest deploying AllowMicrosoft merged with Recommended block rules, as base policy, and then either create individual supplemental policies for each 3rd party app or create a supplemental policy for all 3rd party apps and deploy them,

* Realistically, if it's your personal system with a dynamic workflow then the upkeep of a fully managed system with the type of policy you have in mind is gonna be huge. I personally deployed a Signed WDAC policy using ISG and it authorizes the majority of my apps and lets me install/update/uninstall them, for the rest I just create supplemental policies and rebootlessly deploy them.

Btw I'm curious which template in my repo you were referring to? For WDAC everything is integrated in [a module.](https://github.com/HotCakeX/Harden-Windows-Security/wiki/New-ConfigWDAC) 🙂

**Comment by HotCakeX** [comment]
Hi,

* If you are using latest Windows 11 22H2 version and also using Memory Integrity in Microsoft Defender, then you don't need to merge Microsoft recommended block rules as they're already deployed and enforced automatically.

* For better manageability and maintenance, I suggest deploying AllowMicrosoft merged with Recommended block rules, as base policy, and then either create individual supplemental policies for each 3rd party app or create a supplemental policy for all 3rd party apps and deploy them,

* Realistically, if it's your personal system with a dynamic workflow then the upkeep of a fully managed system with the type of policy you have in mind is gonna be huge. I personally deployed a Signed WDAC policy using ISG and it authorizes the majority of my apps and lets me install/update/uninstall them, for the rest I just create supplemental policies and rebootlessly deploy them.

Btw I'm curious which template in my repo you were referring to? For WDAC everything is integrated in [a module.](https://github.com/HotCakeX/Harden-Windows-Security/wiki/New-ConfigWDAC) 🙂

**Comment by SebCT** [comment]
> * If you are using latest Windows 11 22H2 version and also using Memory Integrity in Microsoft Defender, then you don't need to merge Microsoft recommended Driver block rules as they're already deployed and enforced automatically.

That's true, but if you want the latest recommended driver block rules, you can also add them as an additional policy, the last version is 10.0.25310.0 ->

https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules#microsoft-vulnerable-driver-blocklist

"Customers who always want the most up-to-date driver blocklist can also use Windows Defender Application Control (WDAC) to apply the latest recommended driver blocklist contained in this article."

Additionally an explicit allow list for drivers is also recommended.

**Comment by HotCakeX** [comment]
@SebCT Yes definitely, that's why I made this:
[Fast and Automatic Microsoft Recommended Driver Block Rules updates](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Fast-and-Automatic-Microsoft-Recommended-Driver-Block-Rules-updates)

It does its job separately and automatically.

About allowing drivers, I haven't personally seen any of my hardware drivers being blocked and need me to allow it manually, have you?

**Comment by SebCT** [comment]
> @SebCT Yes definitely, that's why I made this: [Fast and Automatic Microsoft Recommended Driver Block Rules updates](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Fast-and-Automatic-Microsoft-Recommended-Driver-Block-Rules-updates)
> 
> It does its job separately and automatically.

Very nice! :-)
 
> About allowing drivers, I haven't personally seen any of my hardware drivers being blocked and need me to allow it manually, have you?

I use the DefaultWindows_*.xml as a baseline (https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/example-wdac-base-policies) and supplemental rulesets - and a seperate policy for recommended block and recommended driver block rules. - so if a driver has WHQL it won't be blocked.

But on a corporate device i have explicit allowlisting with Publisher Certs to allow - if the Publisher certs are changing, i have to allowlist the new certificate. The most secure would be to go to the filename and fileversion PE property in combination with the Pubsliher certificate - it's very demanding to maintain (i do this on a seperate test device) and something a home user wouldn't want to do :-)

**Comment by HotCakeX** [comment]
Thank you!

That's a nice config :)
I wish all corporations and enterprises would do that to some extent, we'd see a lot less ransomware attacks and things like that.

**Comment by dennyamarojr** [comment]
Hi @HotCakeX , really to nice to see you here =) 

I'm using Windows 11 22H2 and yes I will need to re-create the template due Microsoft integrate the Driver Block rules into windows 11.
The template I try is the AllowMicrosoftPlus that you provide in the project and I really love how the project works and I'm using the project and check everyday for an update :)

And yes I'm using in my personal computer and I'm trying to create a really restrict template to allow only the programs whitelisted in the WDAC Template and prevent any other programs to run. Also, I'm testing to make sure that is someday I use a corporate device or even another device that I want just use just a small amount of programs, I could restrict to this small list of programs.

And also, the file rules is one of the things I had to learn what is the best for both scenarios enterprise and home user.

Another thing is that I want to configure my parents computer too, so I could restrict the programs and games in the kids computer 😁 and know the right config for each scenarios.

**Comment by HotCakeX** [comment]
> Hi @HotCakeX , really to nice to see you here =)
> 
> I'm using Windows 11 22H2 and yes I will need to re-create the template due Microsoft integrate the Driver Block rules into windows 11. The template I try is the AllowMicrosoftPlus that you provide in the project and I really love how the project works and I'm using the project and check everyday for an update :)
> 
> And yes I'm using in my personal computer and I'm trying to create a really restrict template to allow only the programs whitelisted in the WDAC Template and prevent any other programs to run. Also, I'm testing to make sure that is someday I use a corporate device or even another device that I want just use just a small amount of programs, I could restrict to this small list of programs.
> 
> And also, the file rules is one of the things I had to learn what is the best for both scenarios enterprise and home user.
> 
> Another thing is that I want to configure my parents computer too, so I could restrict the programs and games in the kids computer 😁 and know the right config for each scenarios.

Hi ^^ Thank you! Happy to know you've been using the module 😊I actually updated it to version 0.0.9 today, one of the new features is that it auto updates itself so you will always run the latest version of it ^^

You can achieve all of your goals easily with the module, but there are lots of maintenance involved. Like when you deploy it to your parents computer and allow them to use the installed programs, what happens when the programs need update?

if they are Windows store installed programs then it's very easily to allow them once in a policy and later version will be allowed to run and updated as well.

If the non-Windows store program that you are trying to allow is digitally signed (all of its files) then it's easy to allow its files to run and the program itself be updated when a new version is released.

If the program is non-Windows store and doesn't have a digital signature (most open-source programs are like this) or it has digital signatures but not all of its files are signed, then you have a maintenance issue where you need to update the supplemental policy every time the app updates because you use file hashes to allow the non-signed files and they change every time they are updated.

You can also consider using Smart App Control. It's one step higher than a WDAC policy for a lightly managed system (ISG), it's very solid and secure.

If you have other ideas about the maintenance and how to make them easier for a fully managed system, please let me know! I can implement them in the module :)

**Comment by dennyamarojr** [comment]
From the moment, I'm trying to implement everything in my personal computer @HotCakeX and them see what is the issues I will face while making the template, and yes I will need to create 2 templates which is more safe since the supplemental template could have some options to make things easy and no issue when we deploy it. 

For the project @HotCakeX  I guess the only thing in the moment I think is create a section call Beginner and Advanced and describe all these steps and recommend the process you tell me earlier, so everyone could try in their own environment.
For beginners, use AllowMicrosoftMode or SignedAndReputable with a few rules that will easy allow the programs and also use ISG, for Advanced user we could recommend 2 templates one as the base and other as the supplemental, so the supplemental policy could be easily managed and allow 3rd-party apps/programs.

**Comment by HotCakeX** [comment]
That sounds good! I'll add more scenarios based on what you said and new pages to the wiki in the next few days :)

**Comment by dennyamarojr** [comment]
To close this issue, for the base template I create something like this:

- **Template mode:** AllowMicrosoftMode for base template.
- Policy Rules
  - 0 Enabled:UMCI
  - 2 Required:WHQL
  - 5 Enabled:Inherit Default Policy
  - 6 Enabled:Unsigned System Integrity Policy (Default)
  - 9 Enabled:Advanced Boot Options Menu (maybe?)
  - 11 Disabled:Script Enforcement
  - 12 Required:Enforce Store Applications
  - 16 Enabled:Update Policy No Reboot
  - 17 Enabled:Allow Supplemental Policies
  - 19 Enabled:Dynamic Code Security
  - 20 Enabled:Revoked Expired As Unsigned
- Merge with Recommended User Mode Block Rules (Recommended Block Rules, in the WDAC is called User Mode Block Rules)
- And deploy it to the system

For the supplemental template, something like this:
- Policy Rules, add **ISG**
  - 14 Enabled:Intelligent Security Graph Authorization

And them add the 3rd party apps/programs, but not sure if without ISG the apps will still running, but what do you think @HotCakeX

**Comment by HotCakeX** [comment]
That sounds good overall. You can first test the policy with Boot to audit on failure and Advanced Boot Options Menu. Once you know the base policy works on your system then remove those policy rule options and deploy it without them.

You can do the same automatically with `-TestMode` switch parameter of the module too.

ISG for supplemental policy is interesting. So you have 1 base policy, AllowMicrosoft, and 1 supplemental policy, using ISG. Deploy them, if anything gets blocked, you can add them to the same supplemental policy that has ISG rule.

Without ISG only Microsoft signed programs will work, no 3rd party :)

**Comment by HotCakeX** [comment]
Btw in Windows insider Canary channel builds, the CITool has new features. It can show whether a deployed policy is signed or not, it can show which policy rule options are included in each deployed WDAC policy etc.

**Comment by dennyamarojr** [comment]
That sounds really good, hope to see in the stable versions of windows @HotCakeX 
Thanks for the help. Closing this issue since the problem is solved by the provided informations enough to fix the problem =)

**Comment by HotCakeX** [comment]
Anytime, glad I could help 😇
