### ISSUE TITLE
Documentation for default template policies is incorrect?

### ISSUE THREAD

**Issue by Wh00T** [MicrosoftDocs/WDAC-Toolkit#23]
https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/master/WDAC-Policy-Wizard/docs/using/base-policy.md
https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/master/WDAC-Policy-Wizard/docs/using/supplemental-policy.md

Both files state:

Template Policy | Authorizes the | Circle of Trust
-- | -- | --
Allow Microsoft Mode | Microsoft Office365 Applications<br/>Microsoft Store Applications | Smallest Circle-of-Trust
Windows Works Mode | Microsoft Office365 Applications<br/>Windows-signed Applications<br/>WHQL Kernel Drivers |  
Signed and Reputable Mode | Microsoft Office365 Applications<br/>Microsoft Store <br/>ApplicationsWindows-signed Applications<br/>WHQL Kernel Drivers<br/>Files with good reputation, according to the ISG | Largest Circle-of-Trust

But as per the "decision guide" within WDAC wizard, the "Windows Works Mode" is the one with the smallest Circle-of-Trust and the pre-inlcuded stuff is not aligned with the documentation.

![image](https://user-images.githubusercontent.com/1562582/106091080-ee093180-612b-11eb-96af-4e5a21fc19aa.png)

+It might be helpful to align the docs here with the official docs for base policy templates (because the official docs are the ones that are linked in the wizard itself):
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/example-wdac-base-policies
As per the official docs I'd assume that WDAC wizard uses those default Windows templates as a baseline but I might be wrong. At least it's confusing (just for me maybe? ;))

Mode | Windows base template
-- | --
Allow Microsoft Mode | AllowMicrosoft.xml
Windows Works Mode | DefaultWindows.xml
Signed and Reputable Mode | Maybe DefaultWindows + ISG Rule Option?

**Comment by jgeurten** [comment]
@Wh00T, You are absolutely right, the Windows template is the smallest circle of trust. I cannot believe I 1) made this mistake in the first place, 2) have never caught it before. Thanks so much for bringing this to my attention.
