### ISSUE TITLE
Problem with creating allow rules for (most likely) kernel protected files

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/WDAC-Toolkit#238]
I've been trying to create an allow rule for an executable in an Xbox game pass game called Disc Room but it's not working the way I thought it would.

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/c2e765cf-5148-411f-97a6-1d9842da7b7b)

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/cda13103-4960-42cb-8b98-847044bc460c)

Scanning the folder where the file is located (Level = Hash) using WDAC Wizard or cmdlets directly, creates a policy that includes everything except for that file.

I've tried using DriverFiles and PFN level too but no luck. Is this one of the shortcomings of WDAC or am I missing something?

**Comment by jgeurten** [comment]
Looking into this. I'm guessing the Wizard and the powershell cmdlets don't have privileges to scan protected media like this but we'll check with the file system and xbox team

**Comment by HotCakeX** [comment]
@jgeurten Thank you, btw WDACConfig module can now automatically detect and create allow rules for those files

* [Edit-WDACConfig [-AllowNewAppsAuditEvents]](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Edit-WDACConfig#edit-wdacconfig--allownewappsauditevents)
* [Edit-SignedWDACConfig [-AllowNewAppsAuditEvents] ](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Edit-SignedWDACConfig#edit-signedwdacconfig--allownewappsauditevents)

**Comment by jgeurten** [comment]
Very cool! How did you get around the permissions issue?

**Comment by HotCakeX** [comment]
> Very cool! How did you get around the permissions issue?

Thank you, I figured since kernel can get their hashes and stores them in event viewer logs, I don't have to do it myself.

So I added one more step to those cmdlets by searching in the user selected directoy(s) for any executables that throw `[System.UnauthorizedAccessException]` when `get-filehash` tries to access it. I collect the location of those exes, look for them in event viewer logs between the time the cmdlet was first run by user till the time the scan begins, extract their hashes and add them to the Supplemental policy.

**Comment by HotCakeX** [comment]
Speaking of PFN rule, I noticed WDAC Wizard doesn't create rules for a packaged app's dependency.

Part of the policy made by WDAC Wizard

```xml
<FileRules>
    <Allow ID="ID_ALLOW_PFN_0_0_0" FriendlyName="Allow packaged app by Package Family Name (PFN): DevolverDigital.DiscRoomWin10_6kzv4j18v0c96" PackageFamilyName="DevolverDigital.DiscRoomWin10_6kzv4j18v0c96" MinimumFileVersion="1.0.0.0" />
  </FileRules>
```

Part of the policy made by my module

```xml
<FileRules>
    <Allow ID="ID_ALLOW_A_1" FriendlyName="DevolverDigital.DiscRoomWin10_6kzv4j18v0c96 FileRule" MinimumFileVersion="0.0.0.0" PackageFamilyName="DevolverDigital.DiscRoomWin10_6kzv4j18v0c96" PackageVersion="1.0.5.0" />
    <Allow ID="ID_ALLOW_A_2" FriendlyName="Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe FileRule" MinimumFileVersion="0.0.0.0" PackageFamilyName="Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe" PackageVersion="14.0.30704.0" />
  </FileRules>
```

**Comment by jgeurten** [comment]
That's a good point. I'll add that now
