### ISSUE TITLE
Policy binary file not created automatically

### ISSUE THREAD

**Issue by Wh00T** [MicrosoftDocs/WDAC-Toolkit#24]
As per the docs it should generate a policy file in XML and binary format.
https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/master/WDAC-Policy-Wizard/docs/using/base-policy.md#5-building-the-policy

But at least in my case, it only generates the XML file:

![image](https://user-images.githubusercontent.com/1562582/106092963-b13f3980-612f-11eb-93a7-8177d21658a3.png)

I've tried to run the WDAC wizard as an admin but had the same result > no binary file.
Windows 10 x64 20H2 virtual machine, latest wizard version
![image](https://user-images.githubusercontent.com/1562582/106093357-696ce200-6130-11eb-8c67-65163f621fb3.png)

**Comment by WildByDesign** [comment]
@Wh00T  You need version 1.6.2 of the app. The documentation seemed to be updated prior to the app itself getting pushed to their Azure download site.

Try this: https://webapp-wdac-wizard.azurewebsites.net/packages/WDACWizard_1.6.2.0_x64_8wekyb3d8bbwe.MSIX

There is an issue currently with the settings being lost when visiting the Application Settings, but aside from that the binary conversion in this latest version is working great. To avoid the settings being lost, go to the Application Settings to enable the new binary conversion setting, then never visit the Application Settings page again until a new version with a fix for that is released. Visiting the Settings page is what wipes out your settings at the moment with regard to that bug.

**Comment by jgeurten** [comment]
@Wh00T, @WildByDesign is correct. The latest version of the app is needed for binary conversion. By default, it is disabled in the Settings page. 

Version 1.6.2.2 fixes an issue where the settings would not persist if the Settings page was revisited multiple times, also. 

Thanks so much for bringing these issues to my attention. I have updated the docs too
