### ISSUE TITLE
Some WDAC policies after merge have large runs of zeros appended to their IDs

### ISSUE THREAD

**Issue by jgeurten** [MicrosoftDocs/WDAC-Toolkit#247]
E.g.

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/36230907-a3a9-479d-8ecb-b20c9824e1b4)

I suspect it has to do with merging policies

**Comment by Sekers** [comment]
I think this may be related: when I open and save a policy (even with no changes), it appends "_0" to the rule IDs.

**WDAC Wizard Version:** 2.3.0.1.22

**Reproduce Steps:**
1. Open example file such as "AllowAll.xml".
2. Click Next through wizard until it saves the file.

**Results**
Original:
`  <FileRules>`
`    <Allow ID="ID_ALLOW_A_1" FileName="*" />`
`    <Allow ID="ID_ALLOW_A_2" FileName="*" />`
`  </FileRules>`

New Version:
`  <FileRules>`
`    <Allow ID="ID_ALLOW_A_1_0" FriendlyName="" FileName="*" />`
`    <Allow ID="ID_ALLOW_A_2_0" FriendlyName="" FileName="*" />`
`  </FileRules>`

Every time you update the policy, it keeps appending the "_0" so for example the first rule after a few updates becomes "ID_ALLOW_A_1_0_0_0_0_0".
