### ISSUE TITLE
Supplemental Policies leave Rule 17 on the xml file

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/WDAC-Toolkit#251]
When using WDAC Wizard to create a Supplemental policy you need to point to the base file. Upon creation the supplemental policy will still have the rule 17 enabled.

`    <Rule>
      <Option>Enabled:Allow Supplemental Policies</Option>
    </Rule>
`

When creating a policy on Intune via the new "Application Control" feature (https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer) it will fail to create policies based on XML files.

When removing the Option 17 entirely from the XML file, the policy is then created without issues.

**Comment by jgeurten** [comment]
Confirmed the error: 

[ERROR]: Exception encountered in ConvertPolicyToBinary(): System.Management.Automation.CmdletInvocationException: Only base policy can have allow supplemental policy option. ---> Microsoft.SecureBoot.UserConfig.CIPolicyException: Only base policy can have allow supplemental policy option.
   at Microsoft.SecureBoot.UserConfig.XmlPolicy.SIConvertToBinaryFile(String binaryFilePath)
   at Microsoft.SecureBoot.UserConfig.ConvertFromCIPolicyCommand.ProcessRecord()
   --- End of inner exception stack trace ---
