### ISSUE TITLE
WDAC Managed Installer with Microsoft Deployment Toolkit MDT

### ISSUE THREAD

**Issue by Admin-Center** [MicrosoftDocs/WDAC-Toolkit#264]
Hi, we are deploying Windows 10 using MDT. Is it possible to mark MDT as a managed installer?

**Comment by Admin-Center** [comment]
Thanks for the message. MDT performs Windows installations, but also installations of additional software such as Office/Adobe etc.
Designating the MDT executables as a managed installer didn't help. Below is the XML content. The WDAC documentation says that only EXE files can be a managed installer.
Will WDAC be compatible with MDT?

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<AppLockerPolicy Version="1">
<RuleCollection Type="Dll" EnforcementMode="AuditOnly">
<FilePathRule Id="86f235ad-3f7b-4121-bc95-ea8bde3a5db5" Name="Benign DENY Rule" Description="" UserOrGroupSid="S-1-1-0" Action="Deny">
<Conditions>
<FilePathCondition Path="%OSDRIVE%\ThisWillBeBlocked.dll"/>
</Conditions>
</FilePathRule>
<RuleCollectionExtensions>
<ThresholdExtensions>
<Services EnforcementMode="Enabled"/>
</ThresholdExtensions>
<RedstoneExtensions>
<SystemApps Allow="Enabled"/>
</RedstoneExtensions>
</RuleCollectionExtensions>
</RuleCollection>
<RuleCollection Type="Exe" EnforcementMode="AuditOnly">
<FilePathRule Id="9420c496-046d-45ab-bd0e-455b2649e41e" Name="Benign DENY Rule" Description="" UserOrGroupSid="S-1-1-0" Action="Deny">
<Conditions>
<FilePathCondition Path="%OSDRIVE%\ThisWillBeBlocked.exe"/>
</Conditions>
</FilePathRule>
<RuleCollectionExtensions>
<ThresholdExtensions>
<Services EnforcementMode="Enabled"/>
</ThresholdExtensions>
<RedstoneExtensions>
<SystemApps Allow="Enabled"/>
</RedstoneExtensions>
</RuleCollectionExtensions>
</RuleCollection>
<RuleCollection Type="ManagedInstaller" EnforcementMode="AuditOnly">
<FilePublisherRule Id="e6fe48d9-dde8-44d0-9c0f-d0b16f301976" Name="MICROSOFT.MANAGEMENT.SERVICES.INTUNEWINDOWSAGENT.EXE wersja dokładnie 1.68.105.0 w MICROSOFT® INTUNE™ od O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FilePublisherCondition PublisherName="O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US" ProductName="MICROSOFT® INTUNE™" BinaryName="MICROSOFT.MANAGEMENT.SERVICES.INTUNEWINDOWSAGENT.EXE">
<BinaryVersionRange LowSection="1.68.105.0" HighSection="*"/>
</FilePublisherCondition>
</Conditions>
</FilePublisherRule>
<FileHashRule Id="346ef93e-5fe7-4aaf-a5d1-73597b9548c2" Name="Credentials_scripts.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x456CBB3385580F1374491C3105CE72B04217FF64C826046B12B3CFD10D975AFC" SourceFileName="Credentials_scripts.vbs" SourceFileLength="2621"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="7a3b7b14-05d6-482e-974f-66d65b1bbd8b" Name="DeployWiz_AdminPassword.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x0F7B4952E0D755F0FFE3588B4D1746661AD66D83A4D2C76CA677C65B07360EC8" SourceFileName="DeployWiz_AdminPassword.vbs" SourceFileLength="906"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="c517a0a4-70e0-4662-86d1-aa9d5c85f626" Name="DeployWiz_Applications.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xBDED878A0D77EDC84E02606E88F53D48407C27964B41A1A8973F479E9E64B406" SourceFileName="DeployWiz_Applications.vbs" SourceFileLength="3472"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="b1ae0e95-0cc8-47f4-910d-853325fc368e" Name="DeployWiz_BitLocker.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xB282F877EF78D85A03584643120701B17BA20FEE416745ECF08CE6C4FF5841F0" SourceFileName="DeployWiz_BitLocker.vbs" SourceFileLength="5005"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="bdcc233f-fe98-469c-905a-fdb084d3e6e4" Name="DeployWiz_CaptureImage.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x0C90F18DA9FA7B7AE9E7F8B0DEE5A552E65022E5F10E58D1A122EBE1EFCC9CE2" SourceFileName="DeployWiz_CaptureImage.vbs" SourceFileLength="2892"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="99dd5f2c-7d7a-4740-ac80-bfac880cd221" Name="DeployWiz_ComputerBackup.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x301FDCA7D0AFD670791AC242619DBCC3AF3E8F8D06227E387BDDEE52C72396AF" SourceFileName="DeployWiz_ComputerBackup.vbs" SourceFileLength="2694"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="993283ed-40fe-4196-83d1-1eae160edb3e" Name="DeployWiz_ComputerName.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xB07C3789BA8B65DE1FAEE0746B59F471DC762C3C593AAE5C44A6BD2F7BD5F8C3" SourceFileName="DeployWiz_ComputerName.vbs" SourceFileLength="10091"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="0d136c42-c173-4250-b195-a669809b3d88" Name="DeployWiz_Credentials.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x7D4FC8CB3047249240BC18601B2D38EC45F672602E3054A73774A06AF7468598" SourceFileName="DeployWiz_Credentials.vbs" SourceFileLength="1249"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="4a509ec6-0c82-4a56-9b86-902a05852022" Name="DeployWiz_Initialization.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x6657DE24148228787255FDB1F88EFC435A2D66331E125B625444FD7B3C272AE4" SourceFileName="DeployWiz_Initialization.vbs" SourceFileLength="6831"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="a290a883-3ebf-4e99-aea0-7b45c84d80e9" Name="DeployWiz_LanguagePack.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x6041D37EE49C8C1C6F9CD2349D3CDBDD5C2BF36C54970EF5868A3FFDE0F2491B" SourceFileName="DeployWiz_LanguagePack.vbs" SourceFileLength="7767"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="b58e5a18-a0c6-46ba-a50e-49754b0ffe50" Name="DeployWiz_LanguageUI.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x820E5F12427C3619AD9EDB16E3D80E952AE46D7DBB8CD0450BF2525AEC9DA144" SourceFileName="DeployWiz_LanguageUI.vbs" SourceFileLength="14763"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="699514fb-4776-4811-8833-81978c0401c7" Name="DeployWiz_OfflineData.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x4507043D889041B17D6F6DA71F22D53DB674979E8D43345E56A8A7CCB333E694" SourceFileName="DeployWiz_OfflineData.vbs" SourceFileLength="11195"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="790206ed-fe71-4f07-a42e-9a3403578f9f" Name="DeployWiz_ProductKeyVista.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xF9532CF7A8CAF94E127D07A773CB305E85780BC442F3541AA34C16380DED1E7A" SourceFileName="DeployWiz_ProductKeyVista.vbs" SourceFileLength="5174"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="a79d4137-3d6f-4bfa-8d0f-fe32a0041412" Name="DeployWiz_Ready.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xA4D108923B00C3F0ADEF6722F2A1EF073E0A2B9A419F4BB07309BEC35E6B14B7" SourceFileName="DeployWiz_Ready.vbs" SourceFileLength="3926"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="99b2c8d3-fda4-437b-a3fc-e932e74f7ddb" Name="DeployWiz_Roles.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x3342D3B66051448B6A1D98E30B9451EECBD70C6F98A3317883DD833C25334D9B" SourceFileName="DeployWiz_Roles.vbs" SourceFileLength="6312"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="f829bc15-841d-4e75-8f1f-7b800b4dc32e" Name="DeployWiz_SelectTS.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xB2437A5BAC3F1BD75C5980C47A33D8A30A57FD90ED887866EC81F7F73D46C29B" SourceFileName="DeployWiz_SelectTS.vbs" SourceFileLength="3171"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="9c827b4a-db7e-4551-a98f-75e56a497ff1" Name="DeployWiz_UserData.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x5B027FB611706865BDC70C32C775891BBCC2E8B1A36845E3085B2898749E955B" SourceFileName="DeployWiz_UserData.vbs" SourceFileLength="2501"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="6129ea16-9e58-4c43-aee3-8c9d80a11743" Name="DeployWiz_UserDataRestore.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xBADEE17BC89C44A49A411FAA54294D86D0A6A0D7C32473FD19E2AE8BEFD00AA5" SourceFileName="DeployWiz_UserDataRestore.vbs" SourceFileLength="2839"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="37ebf639-ad64-48e9-952c-e2d2a2cee18e" Name="DeployWiz_Validation.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xD890602E374BFB5C5A3539D19C78E209C8B7AC9E68414DFBDB86E7AE647A977A" SourceFileName="DeployWiz_Validation.vbs" SourceFileLength="487"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="6ebc67ec-999d-4baf-b4b2-25d3c61e089f" Name="LiteTouch.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x8541FF22449311CC2E154E0E6DC27398C17ED7860D4A1A1297699875A038D965" SourceFileName="LiteTouch.vbs" SourceFileLength="2987"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="00dd3def-6902-4525-9ef4-dc1ab6704738" Name="LTIBootstrap.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x91B664AAF14E9F16D3B74A61CC1D091F56BB45A7AB5746DBA0A167BF8B4C8799" SourceFileName="LTIBootstrap.vbs" SourceFileLength="2020"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="74c61798-d90c-4e68-83ab-722973b68b76" Name="OSDBranding.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x201309DE1F5803F6FE0E0AACD0941A08E36B4AE7C84119D38429741CF0ADD3C0" SourceFileName="OSDBranding.vbs" SourceFileLength="18375"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="b8a64c8e-2194-440e-9e1c-7f06abba3818" Name="OSDBrandingx64.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xA8D6F1D003A39F32FA2C9388561B77866B542C345ADB163E351EF56195C23E5A" SourceFileName="OSDBrandingx64.vbs" SourceFileLength="18040"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="ec86b58b-c757-4148-8284-4eeee1513c33" Name="OSDEndTime.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x1B929316F33F266519CA9F791C74DAE18BB3FADC7217AB68F03E08941CA8E934" SourceFileName="OSDEndTime.vbs" SourceFileLength="1346"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="7613c754-7afb-4283-9b2c-d3521b9acc74" Name="OSDLocalAdmins.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x98B0215FA78FD556B8034C0C98C24F32084C63A40EC0DEB5E266C02AF03D5B1F" SourceFileName="OSDLocalAdmins.vbs" SourceFileLength="2962"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="9eb05c41-bf89-4576-805e-06b8f120ddae" Name="OSDProgress.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xF46BBE640D6379F3C6981455CB30CC683DC4F3AC727B531FC36758C9A2A238EF" SourceFileName="OSDProgress.vbs" SourceFileLength="22840"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="fb664839-cd9f-4726-bc75-cd9afa3cada9" Name="OSD_BaseVariables.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xB37FA96210A1FC720F62DF491825048209656D4C8D7458CD9C43E3D3F372764A" SourceFileName="OSD_BaseVariables.vbs" SourceFileLength="18309"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="9562add1-574b-49fb-953b-6035ebbeb14d" Name="Summary_scripts.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x7D3D475A09C9918BFCB01DF99ECADD2384A88DBDFC617A74946CDC5D69356AD4" SourceFileName="Summary_scripts.vbs" SourceFileLength="2055"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="8dc03b5b-5799-4379-83aa-52ea381eb1f9" Name="WelcomeWiz_Choice.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xFFFE3F116B25342972A64C7C3B341D987AED7AA915D41000FC453F9B5D378BC5" SourceFileName="WelcomeWiz_Choice.vbs" SourceFileLength="6680"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="79f66f4f-3dac-45ca-b9e3-de8500cffc71" Name="WelcomeWiz_DeployRoot.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xCA4436B5621C13E421B30258E55ECC4F61F16FE3BE6EFDF7C798A1FE7EC3CE88" SourceFileName="WelcomeWiz_DeployRoot.vbs" SourceFileLength="6825"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="198ffb1b-fd33-4f78-ba6e-24acba0a815b" Name="WelcomeWiz_Initialize.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x39731F6AEE4BE2DD01E038A1CED0022A9F8BA3174195178582A2B1E94569F8A2" SourceFileName="WelcomeWiz_Initialize.vbs" SourceFileLength="1696"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="ea1afb81-f39b-4634-b6db-0fa397032be5" Name="WizUtility.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x18B75ABD6685B02A62A6BEA864D88FC3C029BD48FB6C4B6A22DAC1F02E8E46A3" SourceFileName="WizUtility.vbs" SourceFileLength="14551"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="25ddb535-307c-4045-b28f-c915e5f5a5c5" Name="ZTIBCDUtility.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x0FB6ACCB78EBA430C129943E3BEED717DC9C147AB4B07B7CA813C234C87024EF" SourceFileName="ZTIBCDUtility.vbs" SourceFileLength="21881"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="1655541e-1b90-4081-a90c-51835e65c21b" Name="ZTIConfigFile.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xDDE9864423723C66703C0F208CA5523D15F4A9394A3E42535D1888DD199BCC8C" SourceFileName="ZTIConfigFile.vbs" SourceFileLength="25686"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="aa3dcb9f-323d-4eb2-a025-3a7ce07c74c0" Name="ZTIConfirmDiskpart.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x1610A28EEE21203E26811ADFFC0390362C354D27D732A57C57A73E1EB2FCF64F" SourceFileName="ZTIConfirmDiskpart.vbs" SourceFileLength="977"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="a314514a-0061-4f79-826b-9847e3fd5d8b" Name="ZTIDataAccess.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xE595B23E656B603A701A6ECB0264B37BBDC86C316D0F5A9524DB021412A3A6D3" SourceFileName="ZTIDataAccess.vbs" SourceFileLength="25742"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="30c25b02-cd4f-4eec-bf00-a8430b0b75ad" Name="ZTIDiskUtility.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x0F652CC095F42F5BB1964BA6DD09EC9AF699D19ACA1358D3301838154700EF6F" SourceFileName="ZTIDiskUtility.vbs" SourceFileLength="23763"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="6330e169-7da6-49d3-9504-4810b94de52b" Name="ZTINicUtility.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x1DD548C2CDBB8C8B9312F59300ECFB0A4087B8373D494FFF86B575A5160DE706" SourceFileName="ZTINicUtility.vbs" SourceFileLength="19297"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="c484a1de-6214-4e5c-954b-3b15abdbe3df" Name="ZTIPrereq.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xFBD04D185E3A736BF3349DB17D9EDA8B583383F0D0D7208B03858B2E076BD664" SourceFileName="ZTIPrereq.vbs" SourceFileLength="2795"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="65d07a41-0d64-456d-aa28-0973070824ce" Name="ZTIPSUtility.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0x003806D9458CC9631A1E667CEEEA717B2FFC9D7AC17E1F4336785E7BA31D73C4" SourceFileName="ZTIPSUtility.vbs" SourceFileLength="3207"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
<FileHashRule Id="46ce62ef-f5ba-4dd7-a4a6-a9f6e8deea01" Name="ZTIUtility.vbs" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
<Conditions>
<FileHashCondition>
<FileHash Type="SHA256" Data="0xBF409B7FD18A8F94E4E09DDB3C82DEF97C72F16CB0EAF13918F87BBF06F76961" SourceFileName="ZTIUtility.vbs" SourceFileLength="136801"/>
</FileHashCondition>
</Conditions>
</FileHashRule>
</RuleCollection>
</AppLockerPolicy>`

**Comment by jgeurten** [comment]
What is the process writing the files to the system, though? Is it MDT or Config manager?

**Comment by Admin-Center** [comment]
MDT

**Comment by jgeurten** [comment]
vbs files cannot be set as a managed installer, unfortunately. Only EXEs can be set - https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/configure-authorized-apps-deployed-with-a-managed-installer#configure-managed-installer-tracking-with-applocker-and-wdac
