### ISSUE TITLE
ConvertFrom-CIPolicy: System.OutOfMemoryException

### ISSUE THREAD

**Issue by Harvester57** [MicrosoftDocs/WDAC-Toolkit#269]
Hi,

I'm trying to convert a denylist from XML to binary, and the conversion fails, either while using the ConvertFrom-CiPolicy or the WDAC Wizard (but from what I understand, it is using the cmdlet under the hood, so that's not unexpected).

The denylist is generated from the LOLDrivers.io project, from the drivers found here: https://github.com/Harvester57/LOLDrivers/tree/main/drivers

I initially generated the denylist with `-Level FilePublisher -Fallback Hash` parameters for the `New-CIPolicyRule` cmdlet, but the policy was quite huge (approx. 5000 lines). I then tried to reduce its length by switching to different fallback mechanisms: `-Fallback SignedVersion,Publisher,Hash`

While the second policy is substantially smaller, I hit a second bug when trying to convert the policy to binary:  several `MinimumFileVersion` fields had incorrect values detected by the `New-CIPolicyRule` cmdlet:

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/7060295/a1f6ccd6-f2df-4e88-8d33-d04d822a73aa)

As you can see, `_1` is appended to these attributes, so the ConvertFrom cmdlet fails with a warning related to the schema `'urn:schemas-microsoft-com:sipolicy:VersionExType'`

If I manually fix the version for those attributes, the cmdlet fails again with an OutOfMemory exception.

The two policies can be downloaded as artifacts from the following Github Actions:

- Original policy (Hash fallback): https://github.com/Harvester57/LOLDrivers/actions/runs/5689865986
- Smaller policy (with MinimumVersion bug): https://github.com/Harvester57/LOLDrivers/actions/runs/5692033105

**Comment by jgeurten** [comment]
Internal only I am afraid
