### ISSUE TITLE
WDAC does not show Publisher Deny rule in rules page after being rule was created

### ISSUE THREAD

**Issue by MalovichP** [MicrosoftDocs/WDAC-Toolkit#285]
I am using version 2.3.1.1 x64. And after I created a rule to DENY a PUBLISHER, it created a slightly bigger XML file. But when I go to Edit that newly created XML, the DENY Publisher rule does not show up in the rules panel.

**Comment by jgeurten** [comment]
Hmm I cannot reproduce this. 

What type of publisher rule is it? The rules panel will parse all the publisher rules first, so if your policy has a lot of rules, you will need to scroll near the top of the rules panel and look through the Publisher rule list
