### ISSUE TITLE
Zero ID cleanup causing duplicate signer IDs

### ISSUE THREAD

**Issue by nictau** [MicrosoftDocs/WDAC-Toolkit#287]
Hello,

I have stumbled across a bug that I believe has something to do with the recently introduced cleanup feature where additional _0's are removed on ID's within a policy. (#247)

I have the following signers:
```
    <Signer Name="DigiCert Trusted Root G4" ID="ID_SIGNER_S_1_0_1_1">
      <CertRoot Type="TBS" Value="yyyy" />
      <CertPublisher Value="Vendor 1" />
    </Signer>
    <Signer Name="VeriSign Class 3 Code Signing 2010 CA" ID="ID_SIGNER_S_1_0_1_1_0_0">
      <CertRoot Type="TBS" Value="xxxx" />
      <CertPublisher Value="Vendor 2" />
    </Signer>
```

Upon saving this policy even if I do not make any changes, it will cause the above two signers to have a duplicate ID.
I have a script that converts the XML into binary and first noticed the issue with this output:

```
ConvertFrom-CIPolicy : Rule with Duplicate Id ID_SIGNER_S_1_0_1_1_0
```

I have been on version 2.2.0 until recently, just having upgraded to 2.3.1.
The first few policy modifications were fine, but I seem to have hit an issue with this most recent policy version. I've done about 3 modifications on the new version and cannot now make any newer versions.

If I try to load up the new XML into the WDAC Wizard, I receive:
![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/40283140/0f61bd8b-9e5f-4080-a561-51011f13d515)

**Comment by jgeurten** [comment]
Confirmed bug in the Wizard. @nictau in the meantime, manually update the ID for one of the rules by CTRL+F and searching for all the hits in your favorite text editor
