### ISSUE TITLE
create custom pathrule with folder selected, however FilePath output missing wildcard

### ISSUE THREAD

**Issue by atran1981** [MicrosoftDocs/WDAC-Toolkit#29]
When create custom FilePath Rule, selected Option Folder, However Policy XML output did not have correct FilePath which missing the wildcard at the end. 

![image](https://user-images.githubusercontent.com/79132095/108670285-bdea5e00-7532-11eb-9d38-6e3053bdbfae.png)

**Comment by jgeurten** [comment]
Thank you for filing this issue. I have added it to the WDAC Wizard backlog. Specifically supporting wildcards, as defined here: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#more-information-about-filepath-rules

**Comment by jgeurten** [comment]
Custom filepath rules, wildcards and macros added in #48
