### ISSUE TITLE
Rule IDs get longer when policy is edited?

### ISSUE THREAD

**Issue by ThioJoe** [MicrosoftDocs/WDAC-Toolkit#290]
Converting my discussion to an issue because it seems maybe related to #247 , but not exactly.

#### Discussed in https://github.com/MicrosoftDocs/WDAC-Toolkit/discussions/284
<div type='discussions-op-text'>

<sup>Originally posted by **ThioJoe** August 19, 2023</sup>
Maybe I'm doing this wrong, but I have a single policy file and I just edit it with the WDAC wizard whenever I want to add new rules. So I have a lot of iterations of my policy xml file.  But I noticed the ID values for the rules have gotten longer and longer.

For example, one sample has gone from originally:
```
<FileRuleRef RuleID="ID_DENY_KD_KMCI_0" />
<FileRuleRef RuleID="ID_DENY_AGENT64_SHA1_1" />
<FileRuleRef RuleID="ID_DENY_AGENT64_SHA256_1" />
<FileRuleRef RuleID="ID_DENY_AGENT64_SHA1_PAGE_1" />
<FileRuleRef RuleID="ID_DENY_AGENT64_SHA256_PAGE_1" />
```
to this in version 9:
```
<FileRuleRef RuleID="ID_DENY_KD_KMCI_653_1298_0_0" />
<FileRuleRef RuleID="ID_DENY_AGENT64_SHA1_1_1299_0_0" />
<FileRuleRef RuleID="ID_DENY_AGENT64_SHA256_1_1_646_0" />
<FileRuleRef RuleID="ID_DENY_AGENT64_SHA1_PAGE_1_2_647_1" />
<FileRuleRef RuleID="ID_DENY_AGENT64_SHA256_PAGE_1_3_648_2" />
```

I don't think it adds to it every single time, but it's going to get really messy looking real fast.</div>

-----------------------------

The ID seems to get appended each time there's an edit but it's not always with a zero. Is this intended?

If I recall, I also noticed that at some point when I tried to add additional rules by editing a policy, it wouldn't actually work and add the rule like it said it did.

I could be totally wrong but I think it could be due to these lines:

https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/0898427937c2d434576c36ecc67ffc89161d65dc/WDAC-Policy-Wizard/app/src/Helper.cs?plain=1#L2535

https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/0898427937c2d434576c36ecc67ffc89161d65dc/WDAC-Policy-Wizard/app/src/Helper.cs?plain=1#L2556

https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/0898427937c2d434576c36ecc67ffc89161d65dc/WDAC-Policy-Wizard/app/src/Helper.cs?plain=1#L2577

https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/0898427937c2d434576c36ecc67ffc89161d65dc/WDAC-Policy-Wizard/app/src/Helper.cs?plain=1#L2674

I'm not familiar with how the app works behind the scenes but I'm wondering if it basically loads in the list of rules from the file, then at some point goes to re-write the file and for each rule checks for duplicates, but might be checking against itself somehow so there is always a duplicate detected? 

If that's the case, perhaps have it check whether the existing conflicting rule (with the matched rule ID) has values/contents that are exactly the same as the 'new' one. Which would mean it's not really a duplicate ID, it's just the same unchanged rule, so therefore doesn't increment. Not sure if that's even the problem though, just a thought.

----------------------------------

**Comment by jgeurten** [comment]
Hi @ThioJoe, the growing IDs issue is a result of the Merge-CIPolicy powershell cmd that the Wizard calls to merge all of the policies into 1. The PS command continues to append 0 to the IDs in an effort to ensure uniqueness. 

The Wizard attempts to cap the number of 0's to a max of 3 by evaluating the policy IDs before compilation. I have a new PR out that does a better job of this #291
