### ISSUE TITLE
Add custom file types to File Rules "folder scan"

### ISSUE THREAD

**Issue by tylermontneyacc** [MicrosoftDocs/WDAC-Toolkit#297]
I came across an application which uses an uncommon extension (.bpl) for executable content. As such, I need to add the hash of a large amount of files. Rule type "folder scan" does not include this extension.

Please consider adding a way to include additional extensions in the folder scan. I had to manually calculate the hashes and edit the XML file directly, which is a pain.

**Comment by HotCakeX** [comment]
@tylermontneyacc 
That's how WDAC works (see the supported extensions at the bottom): https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/feature-availability

`.bpl` is not a native Windows executable or PE.

Do you see any Code Integrity logs for `.bpl` files being blocked if you don't allow them in your policy?

Also, how do you manually calculate hashes? Those hashes are not regular SHA256/SHA1 hashes that can be calculated by `Get-FileHash` cmdlet.

They are Authenticode and page hashes.
more info about them: https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/select-types-of-rules-to-create#more-information-about-hashes

**Comment by jgeurten** [comment]
This is correct ^

The folder scan PS command natively scans all native Windows executables, portable executables (PEs). Since bpl files are not PEs, they are not calculated in the folder scan.
