### ISSUE TITLE
Dark mode appearance related issues in version 2.4.0

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/WDAC-Toolkit#309]
# 1

Instead of a filled square that makes the text inside it barely readable because it's still white, there should be a different design, for example use a blue frame around the option instead of a filled square.

<br>

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/5be48907-5034-4455-b794-a81531a46d57)

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/17d78368-be37-4596-9078-894425e4ce72)

<br>

# 2

The black font background should be removed. As you can see in the screenshots, they look bad and they're unnecessary. The text is white, the background is black, there is no need for another shade of black surrounding the texts.

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/c842c327-fe93-46da-9c85-6929e8df125c)

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/7e198e22-5a14-41a7-ab9f-0050cefc4f03)

<br>

# 3

When clicking/tapping/hovering over these buttons, a light blue shape appears which doesn't look good. It can be replaced with an animation, or if animation can't be done then consider removing it.

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/2b1d2890-b84f-4b9d-ada8-e33850fb3c77)

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/3d29c1f2-08d1-4ccf-ad2a-3f2a2897aa4c)

<br>

# 4

This one is a suggestion: What if you use Win UI3 and all the new beautiful elements offered by it and Windows 11 design such as Mica effect etc.?

<br>

# 5

This one required a video recording to show. In the dark mode, when selecting/deselecting a checkbox it stays blue/filled until the mouse cursor leaves that area. The last part shouldn't be necessary. The checkbox should be emptied properly when mouse click happens.

https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/7ddab834-1518-45bf-b47e-633c09ebe252

<br>

**Comment by WildByDesign** [comment]
1 - Can you check this to see if this is OK? (https://github.com/MicrosoftDocs/WDAC-Toolkit/pull/306)
2 - This one was fixed with this PR (https://github.com/MicrosoftDocs/WDAC-Toolkit/pull/305)
3 - I haven't fixed this one yet. There are similar mouseover issues on Template page as well.
4 - Question for Jordan.
5 - This should be a quick and easy fix. I will see if I can make a PR on this.

**Comment by WildByDesign** [comment]
@HotCakeX  Regarding number 5, can you have a look at this and see if this is how you like it?

I will submit a PR soon for Jordan to check the code.

![wdac-settings-checkboxes](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/26308319/7c9f4d3a-384c-4b9f-b271-ad935185731f)

**Comment by HotCakeX** [comment]
@WildByDesign 
Thanks for quick fixing,
Yes, for #5 it looks good

**Comment by WildByDesign** [comment]
You’re welcome. I’m pretty sure that I can use the same (or similar) technique to fix number 4 later as well.

**Comment by WildByDesign** [comment]
@jgeurten Regarding issue number 3 that she pointed out here, I can't seem to find anywhere in the code that would cause this.

**Dark mode:**

In dark mode it only seems to have on click.

![wdac-configpolicy-dark](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/26308319/982e78a1-439b-4e4a-be7d-5ff0ea7e8936)

**Light mode:**

In light mode it happens on mouse over and click. The weird thing is that there are no mouseover events associated with these buttons at all.

![wdac-configpolicy-light](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/26308319/fbd54d64-50bf-4567-a79c-b20d47b8c3de)

I think that this has something to do with the transparency in the PNG toggle images. I found a way to fix this. I tested by filling the background of the toggle buttons (transparent areas) with the appropriate matching background colors. White for the light mode background and RGB 15,15,15 for the dark mode toggle buttons. This fixed the problem 100%.

There was only one remaining problem with this. The `untoggle.png` button is shared between dark mode and light mode. If you could possibly create and add `darkmode-untoggle.png` and add it to the project then I can fix this issue.

This would be more of a workaround. Unless you can find a problem in the code that would cause this.

**Comment by WildByDesign** [comment]
The workaround that I mentioned in the previous comment (above) is unnecessary now since I have figured out a proper (and easy) fix for the issue. Fixed in pull request (https://github.com/MicrosoftDocs/WDAC-Toolkit/pull/331).

This concludes the fixable issues included in this issue. Once that PR is merged, this issue can be Closed.

**Comment by HotCakeX** [comment]
Thank you!

**Comment by WildByDesign** [comment]
You’re welcome.
