### ISSUE TITLE
Dark/Light Button Color Control Issues

### ISSUE THREAD

**Issue by WildByDesign** [MicrosoftDocs/WDAC-Toolkit#313]
I have been planning to do a fix to make all buttons throughout the program all consistent since there are a lot of consistency issues with button colors/styles. However, there are a few issues that are stopping me from proceeding.

I have done pretty comprehensive testing of all of these app pages (below) regarding how they function with the Dark/Light Button Controls for coloring/styling the buttons. Therefore, I put together a chart to make it easier to plan any fixes on these issues.

```
                            Dark/Light             
                            Button                  
Page                        Control     Working          

MainForm                    Yes         Yes (done)        
Settings                    Yes         Yes (done)        
EditWorkflow                Yes         Yes (done)
PolicyType                  Yes         Yes (done)
TemplatePage                Yes         Yes (done)          
EventLogRuleConfiguration   Yes         Yes (done)        
SigningRules                Yes         Yes (done)    
PolicyMerge                 Yes         Yes (done)        
CustomRuleConditionsPanel   Yes         Yes (done)   
Exceptions                  Yes         Yes (done)   

```

Unfortunately, fixing any of these Dark/Light button control issues is beyond my abilities. I have tried a bunch of different things to fix certain pages but I was not able to fix the issues. I also don't understand why the Dark/Light Panel Controls overrides the Dark/Light Button Controls in certain cases.

**EDIT:** I have figured out how to fix these now and have been updating the chart above by adding **Yes (done)** to each one as I submit a PR for each page individually.

**Comment by WildByDesign** [comment]
The work from this issue is now complete and the issue can be closed once the associated pull requests are merged.

**Comment by jgeurten** [comment]
Thanks for all of your work on this, @WildByDesign. It's taken me a while to get to reviewing all of your changes but I appreciate all your hard work!

**Comment by WildByDesign** [comment]
You’re welcome, my pleasure.
