### ISSUE TITLE
MDE Advanced Hunting Events to Policy 

### ISSUE THREAD

**Issue by AlzheimerZA** [MicrosoftDocs/WDAC-Toolkit#320]
Parsing MDE Advanced Hunting Events to policy only caters for an "Allow Rule" to be created.

**Comment by jgeurten** [comment]
Thanks for submitting this issue. This is by design since everything in the table is inherently untrusted. It would be redundant to add support for blocking something that is already blocked.

**Comment by AlzheimerZA** [comment]
Thanks, so the tool is catering only for blacklisting scenarios and not whitelisting?

**Comment by jgeurten** [comment]
No, the flow creates an allowlist of files that were previously blocked (i.e. showed up in MDE AH)
