### ISSUE TITLE
Editing supplemental rules doesnt change the new file.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/WDAC-Toolkit#325]
Using version 2.4.0.0 I edit a supplemental rule (I remove a rule from the policy), the new version of the file saves with the filename containing the incremental version number.

However I see the original file is edited and the incremental version file is not.

**Comment by cgerke** [comment]
Sorry didn't see #296 

This looks like a duplicate.

**Comment by jgeurten** [comment]
Thanks for reporting. You're right, looks like a dupe of #296. Thanks
