### ISSUE TITLE
WDAC - Use -SpecificFileNameLevel with FileName, FilePublisher, or WHQLFilePublisher level rules

### ISSUE THREAD

**Issue by ZazziDBeast** [MicrosoftDocs/WDAC-Toolkit#335]
Would be nice if this was integrated in the GUI:

Use -SpecificFileNameLevel with FileName, FilePublisher, or WHQLFilePublisher level rules

https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/select-types-of-rules-to-create#use--specificfilenamelevel-with-filename-filepublisher-or-whqlfilepublisher-level-rules

**Comment by jgeurten** [comment]
I support all of these options, except for the WHQL publisher field. I worry about the crowdedness of the UI if I were to add all of these options + WHQL inside the publisher UI. 

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/1d62e551-0c41-4026-93b1-90c4b0e9449d)
