### ISSUE TITLE
Cannot parse events from Advanced Hunting CSV

### ISSUE THREAD

**Issue by ocadudeployment** [MicrosoftDocs/WDAC-Toolkit#336]
Using the query described here: 
https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/main/WDAC-Policy-Wizard/docs/using/advanced-hunting.md

when attempting to import the produced CSV from MS Security Center into the WDAC Wizard, we receive "The Wizard could not parse any Advanced Hunting events from the CSV file(s)."

The file matches the requirements as described in said article. There are many relevant events int he exported data: "AppControlCodeIntegrityPolicyAudited", "AppControlCodeIntegrityOriginBlocked", "AppControlCodeIntegrityPolicyBlocked" are some examples of the ActionTypes present.

looking in ...\AppData\Local\Temp\WDACWizard\Temp\2023*\log*.txt shows nothing except for "No Advanced Hunting Records Parsed", no information as to *why*. If I run the WDAC wizard on a target system (whose events are in this export) and tell it to parse the event logs on the local computer, it will produce file rules--so it's not as though there is no parsable data.

**Comment by ocadudeployment** [comment]
Sure @jgeurten here's an example of a query submitted to the wizard.

[WDAC_query.csv](https://github.com/MicrosoftDocs/WDAC-Toolkit/files/13641800/WDAC_query.csv)

**Comment by ocadudeployment** [comment]
@jgeurten my bad...I have discovered that the CSV I submitted does not have the AuthenticodeHash field. However it was in my Advanced Hunting query--it looks like the field returned a blank value and was thus omitted from the export.

I had to select 'Customize Columns' in the Advanced Hunting interface after running the query again, and select the Authenticode Hash column to be displayed for it to be included in the exported CSV.

After doing so, the CSV is parsed successfully by the WDAC Wizard. Might I suggest that since this seems to be the default behavior of Advanced Hunting that if this field is not present, then have the Wizard ignore that and parse the file anyway. You can feel free to close this issue--but please note that either a revision to the documentation or the application is desired.

**Comment by jgeurten** [comment]
hmm that is super odd. I see what you're describing in AH. That's never been an issue before, and I have previous csvs where the Authenticode column is present, but all the data rows are empty. AH must have updated their logic to drop columns where all the data is empty. 

I'll need to fix this as I anticipate others will hit this too in the future

**Comment by lee-halford** [comment]
Update your KQL query from "**project**" to "**project-keep**", otherwise it drops the Authenticode Hash column if the whole column has null values.

**Comment by ocadudeployment** [comment]
@lee-halford that works--thank you.

**Comment by jgeurten** [comment]
Thanks all. I will update the documented KQL query!
