### ISSUE TITLE
Aircall issue

### ISSUE THREAD

**Issue by kylejericson** [MicrosoftDocs/WDAC-Toolkit#341]
I have created rules for C:/Program Files & C:/Users/*/appdata/ .
The app Aircall seems have files in c:/users/*/appdata/local/temp
I get an error trying to open this app.
How can I fix this?
More info on my LinkedIn post here

https://www.linkedin.com/feed/update/urn:li:activity:7156359141479915520?utm_source=share&utm_medium=member_ios

**Comment by jgeurten** [comment]
Hi @kylejericson, 

If you're using Windows 11, you can use this path rule: "C:/*/appdata/local/temp/aircall/*"

https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/select-types-of-rules-to-create#example-filepath-rules-with-wildcards

**Comment by kylejericson** [comment]
I'm on Windows 11 and added this rule and same issue.
<img width="675" alt="Screenshot-11-22-52-AM" src="https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/43736908/4e5702c8-02a3-4923-a883-3d78dff90d0a">

**Comment by kylejericson** [comment]
I wasn’t able to get this to work even with these paths. I then created these rules in App Locker and they worked.
