### ISSUE TITLE
Can't edit policy with ExceptAllowRule: says it's corrupted

### ISSUE THREAD

**Issue by pasqualm** [MicrosoftDocs/WDAC-Toolkit#344]
In a policy, I add a deny rule based on publisher with a file path exception, the process goes ok

Later I try to edit the generated policy and WDAC Wizards shows a 'Parsing error' and doesn't let me edit the file

I upload a sample xml base (parses ok) and another with the ExceptAllowRule added (doesn't parse)
[testcase.zip](https://github.com/MicrosoftDocs/WDAC-Toolkit/files/14358632/testcase.zip)

**Comment by jgeurten** [comment]
Hi @pasqualm, great bug report. I can repro this with your test case so it does appear to be a bug in the Wizard. 

For my reference, seems to be a null exception on line 236 in SigningRules_Control.cs
