### ISSUE TITLE
[Suggestion] Add Flighting Root 2014 to Signed and Reputable Template

### ISSUE THREAD

**Issue by AndreasStenhall** [MicrosoftDocs/WDAC-Toolkit#354]
Applying a WDAC policy to a Windows Insider build in block mode can/will have severe consequences as binaries are signed with Microsoft Development PCA 2014 which is obviously not in the default rules. Suggestion to add this as an option in the GUI.

**Comment by AndreasStenhall** [comment]
Applying a WDAC policy to a Windows Insider build in block mode can/will have severe consequences as binaries are signed with Microsoft Development PCA 2014 which is obviously not in the default rules. Suggestion to add this as an option in the GUI.

**Comment by jgeurten** [comment]
@AndreasStenhall all of our templates have rules to allow the flighting root (Development PCA 2014)

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/8386d174-8870-49d5-9b0e-6e901c6b0fd9)


Did you perhaps disable flight signing?

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/5aa91d2b-2018-484e-81a3-7884828c6e1e)

**Comment by AndreasStenhall** [comment]
I did not disable Flight signing. I guess the problem is that the template "Signed and reputable" does not contain Flighting Root 2014, but the other two templates Default Windows Mode and Allow Microsoft Mode do contain Flighting Root 2014.

**Comment by jgeurten** [comment]
I don't think it was intentional to leave the flighting root off the Signed and Reputable template so I'm going to keep this bug open and evaluate updating the template. Thanks!
