### ISSUE TITLE
Cannot open app package

### ISSUE THREAD

**Issue by kristofferth** [MicrosoftDocs/WDAC-Toolkit#357]
When clicking "[Download the Installer]" on your site https://webapp-wdac-wizard.azurewebsites.net/ I get the error 
"Cannot open app package. The ms-appinstaller protocol has been disabled. Please ask the vendor to update the weblink"

![Capture](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/16348788/d909c6d1-ca9d-405e-93f8-c157f2dc009c)

**Comment by kristofferth** [comment]
It works when downloading through "If your download does not start automatically, click [here.](https://webapp-wdac-wizard.azurewebsites.net/packages/WDACWizard_2.4.2.0_x64_8wekyb3d8bbwe.MSIX)"

**Comment by jgeurten** [comment]
Fixed in the most recent publication of the Wizard. Thanks for reporting!
