### ISSUE TITLE
Inconsistency in WDAC Policy Wizard version (Website vs Application)

### ISSUE THREAD

**Issue by Prochy** [MicrosoftDocs/WDAC-Toolkit#358]
There is a different version in Azure Websites for WDAC Wizard and the real version shown in the app.

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/6740126/d3defc94-7c04-47ac-aaed-209b2fe7082e)

**Comment by jgeurten** [comment]
Good find. Thanks for reporting. I fixed this by updating the appinstaller file on the server
