### ISSUE TITLE
Defender threat hunt .csv file failing to parse in WDAC wizard

### ISSUE THREAD

**Issue by bldm0202** [MicrosoftDocs/WDAC-Toolkit#364]
### Discussed in https://github.com/MicrosoftDocs/WDAC-Toolkit/discussions/363

<div type='discussions-op-text'>

<sup>Originally posted by **bldm0202** April 17, 2024</sup>
Hi everyone, this is my first time on Github and I'm not the most technical of persons.

I am hoping someone can provide some advice about why my Defender Advanced Threat Hunt outputs are not successfully parsing in the WDAC wizard. 

I have followed the threat hunt query template outlined here:
https://github.com/MicrosoftDocs/WDAC-Toolkit/blob/main/WDAC-Policy-Wizard/docs/using/advanced-hunting.md 

I've ensured my .csv output has all the data fields. 

However, in the WDAC wizard policy editor I am not able to parse the threat hunting events and receive an error message. At a loss as to how to troubleshoot further. 

Would appreciate any advice you may have. 

The issue seems very similar to that reported in https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/336; however I can confirm all the data fields are in the csv, including AuthenticodeHash field (though all fields are empty for this).

Many thanks!
![Screenshot 2024-04-17 101944](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/167262620/333c4164-0906-41c1-af45-12d30004018b)

</div>

**Comment by bldm0202** [comment]
The AppData log shows an error but does not indicate cause.

2024-04-17T01-49-27 [INFO]: WDAC Policy Wizard Version # 2.4.2.0
2024-04-17T01-49-27 [INFO]: Session ID: 133493550749946775
2024-04-17T01-49-28 [INFO]: **********************************************************************
2024-04-17T01-49-28 [INFO]: Workflow -- Edit Policy Selected
2024-04-17T01-49-28 [INFO]: **********************************************************************
2024-04-17T01-49-28 [INFO]: ==== Edit Workflow Page Initialized ====
2024-04-17T01-49-32 [ERROR]: No Advanced Hunting Records parsed
2024-04-17T01-49-32 [INFO]: **********************************************************************
2024-04-17T01-49-32 [INFO]: Event Parsing Workflow -- DONE
2024-04-17T01-49-32 [INFO]: **********************************************************************

**Comment by bldm0202** [comment]
When reviewing the file that I'm attempting to parse compared with the file in previous case https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/336; the one thing I notice is variances in the date format.

My file:
![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/167262620/294a77a3-965d-4bb8-b972-abbc0b604284)


The file from case https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/336; (which uploads fine if you include AuthenticodeHash column):
![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/167262620/943a04b7-df71-48e6-9e1a-3f050c8a487c)

So this could be the issue; however, unclear to me why the native export from Defender Threat Hunting would differ.

**Comment by HotCakeX** [comment]
Hi,
After seeing your issue, I compared my MDE Advanced Hunting logs from ~2 months ago with ones I just collected and the timestamp format has changed, but they are still valid DateTime object types

```powershell
"2024-03-07T21:09:58.8275833Z" -as [System.DateTime]
"Apr 15, 2024 11:09:27 AM" -as [System.DateTime]
```

<br>

**Comment by bldm0202** [comment]
> Hi, After seeing your issue, I compared my MDE Advanced Hunting logs from ~2 months ago with ones I just collected and the timestamp format has changed, but they are still valid DateTime object types
> 
> ```powershell
> "2024-03-07T21:09:58.8275833Z" -as [System.DateTime]
> "Apr 15, 2024 11:09:27 AM" -as [System.DateTime]
> ```

Hi HotCakeX, thanks. My Defender threat hunt export failed to parse, but when I took the dates from columns in the spreadsheet provided in the previous case 336, the parsing then worked fine. Must be something to do with the DateTime object that is exporting from my Defender threat hunt exports - the attached example.
[Uploading Book2.csv…]()

**Comment by HotCakeX** [comment]
> > Hi, After seeing your issue, I compared my MDE Advanced Hunting logs from ~2 months ago with ones I just collected and the timestamp format has changed, but they are still valid DateTime object types
> > ```powershell
> > "2024-03-07T21:09:58.8275833Z" -as [System.DateTime]
> > "Apr 15, 2024 11:09:27 AM" -as [System.DateTime]
> > ```
> 
> Hi HotCakeX, thanks. My Defender threat hunt export failed to parse, but when I took the dates from columns in the spreadsheet provided in the previous case 336, the parsing then worked fine. Must be something to do with the DateTime object that is exporting from my Defender threat hunt exports - the attached example. Uploading Book2.csv…

Hi, thank you but i think the file wasn't completely uploaded, can you please upload it again

**Comment by bldm0202** [comment]
[Book2.csv](https://github.com/MicrosoftDocs/WDAC-Toolkit/files/15032161/Book2.csv)

**Comment by AlvinOnTech** [comment]
The log messages indicate an issue with use of substring method. There are two substring calls in AdvancedHunting.cs

```
WDAC-Policy-Wizard\app\src\AdvancedHunting.cs:385:            return string.CompareOrdinal(timestampA.Substring(0, TIMESMP_LNG),
WDAC-Policy-Wizard\app\src\AdvancedHunting.cs:386:                                  timestampB.Substring(0, TIMESMP_LNG)) == 0;
```
These correlate with the two messages in the log file. 

What appears to be occurring is a string comparison of the first 22 (TIMESMP_LNG) digits of the time stamp. As the new time stamp format is less than 22 characters long, it throws the error message.

**Comment by jgeurten** [comment]
This is why I love open source! Thanks for the investigations, @AlvinOnTech, @bldm0202 and @HotCakeX!

I'm going to chat with the Advanced Hunting team but if the default timestamp has been updated from ISO 8601 (UTC timestamps), I'll have to update some logic here. The precision of the ISO 8601 timestamps were nice to perform the correlation between block/audit events and signature events, since AH is still not picking up WDAC log correlation IDs which would make the correlation trivial

**Comment by HotCakeX** [comment]
@jgeurten Anytime ^^

This is how I parse the old and new timestamp format:
https://github.com/HotCakeX/Harden-Windows-Security/blob/74094b710f3ff2ec658e12d51ecdacee58d64406/WDACConfig/WDACConfig%20Module%20Files/XMLOps/Compare-CorrelatedData.psm1#L71

And I believe `EtwActivityId` in the AH output is the same as correlation IDs

https://github.com/HotCakeX/Harden-Windows-Security/blob/74094b710f3ff2ec658e12d51ecdacee58d64406/WDACConfig/WDACConfig%20Module%20Files/XMLOps/Compare-CorrelatedData.psm1#L52C8-L52C10

**Comment by BunnyMeng** [comment]
@jgeurten @AlvinOnTech @HotCakeX @bldm0202 @AArnott 
Hello experts,
Greeting.

I'm support from MDE service. Our cx is facing the issue as well that the timestamp format caused failure to upload Advanced hunting data to WDAC.

Advanced hunting date format:
https://learn.microsoft.com/en-us/answers/questions/387479/timestamp-format-in-ms-atp
MM/DD/YYYY HH:MM:SS

WDAC:
2023-12-11T14:42:09.7617248Z

May I double confirm what is currently recommended solution for cx side？

**Comment by AArnott** [comment]
@bunnymeng please don't spam folks to get attention to an issue. I for one have nothing to do with this repo and can't help you.

**Comment by BunnyMeng** [comment]
Hello Andrew,
This is not spam folks but I'm MDE support with facing same date format issue. Sorry if my question disturb you.

So may I double confirm if there is any expert here to advise current recommended workaround if available？

**Comment by BunnyMeng** [comment]
Hello experts，
May I know if there is any advice about currently recommended solution on the inconsistent date format between MDE and WDAC?

**Comment by jgeurten** [comment]
@BunnyMeng while I fix the bug, you can direct the customer to convert these timestamps to ISO 8601 standard
