### ISSUE TITLE
Creating Allow File Hash Rules get Created as Denied

### ISSUE THREAD

**Issue by carlitog** [MicrosoftDocs/WDAC-Toolkit#386]
Hello, I'm using the latest version of WDAC Wizard (2.4.3.0) and when I edit an existing policy to add an allow file hash rule, it gets created as a Deny rule in the policy file.

e.g.

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23627873/0d1edb45-740b-4f7f-bc9a-0c4537bc12fe)

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23627873/b3fa4864-ec98-44c6-95cb-e255bda76346)

**Comment by jgeurten** [comment]
Thanks for reporting. That was a bad one. Fixed immediately

**Comment by carlitog** [comment]
Thank you!

Cheers

**Comment by AD1280241** [comment]
I was just wondering if there was a timeline to get the updated version? 

The Microsoft page, https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/wdac-wizard references https://webapp-wdac-wizard.azurewebsites.net/, but that shows the same version as the original thread of (2.4.3.0) issue.
