### ISSUE TITLE
WDAC could not create or open the WDAC XML file

### ISSUE THREAD

**Issue by alexgoris** [MicrosoftDocs/WDAC-Toolkit#390]
After successfully seem to have created XML file with WDAC I get the following error: 
![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/173990028/5a87b01a-8a59-4a7b-9206-e5b74dc3ba40)

I can reproduce this error on my desktop, laptop, virtual machine at customer 1 and customer 2.

**Comment by jgeurten** [comment]
Hi @alexgoris can you provide the log file listed in the error window. Thanks
