### ISSUE TITLE
Conflicting Policy ID when creating multiple Supplemental Policies from MDE AH Events

### ISSUE THREAD

**Issue by a-shina** [MicrosoftDocs/WDAC-Toolkit#392]
Hello,

I am running into a major issue when creating multiple Supplemental Policies using the MDE AH events to policy conversion.  After the first and second supplemental policies are created, I noticed the Policy ID generated for both of the supplemental policies is exactly the same which results in a conflict when the policies are pushed to Intune App Control for Business.

See screenshots below:
![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/55485702/96222c5a-fb9a-493d-bf00-45c63ba679cb)

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/55485702/780a058f-e2dc-461c-9bf2-d685af097609)
![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/55485702/da637c8a-cc63-4864-ad39-b21fc197e226)

Any help is appreciated!

Thanks,
Adrian

**Comment by jgeurten** [comment]
You cannot upload these polices as-is. Supplemental policies are generated with the same BasePolicyID and PolicyID. You'll have to update the BasePolicyID so it points to your base policies anyway, so I think it's conceivable to change IDs all the time.

**Comment by jgeurten** [comment]
I will update the PolicyID every flow

**Comment by a-shina** [comment]
Correct, both of these supplemental policies are pointed to one main base policy.  Essentially, I want to have multiple supplemental policies to my base policy.

Thank you,
Adrian
