### ISSUE TITLE
Rule IDs recalculation issue

### ISSUE THREAD

**Issue by obuolinis** [MicrosoftDocs/WDAC-Toolkit#399]
In our company we're introducing version control to our WDAC policy update process and while setting it up I noticed that Rule IDs are getting recalculated after each policy update using WDAC Wizard. And since the Wizard itself is being developed using Git I'm sure I don't need to tell you what that means for the version control of policy xml files.

I would really like to hope that this is a bug, in which case I can provide more details about my observations, but another issue from last year (#290 ) suggests otherwise :(

Can anyone explain such a terrible version-control-unfriendly design of the xml? Can I request it to be reconsidered?

**Comment by byt3f1ire** [comment]
+1 from us
We store the Policy in Github and it makes tracking changes much harder

My current workaround is to run this regex with search and replace before committing to get a "clean" file. So far it didnt break my policy.
Search: (_0)+?"
Replace with: "
