### ISSUE TITLE
Single Policy Format - PolicyID and BasePolicyID

### ISSUE THREAD

**Issue by PaulbBerg** [MicrosoftDocs/WDAC-Toolkit#401]
If you use the WDAC Wizard to create a policy from scratch using the “Policy Creator” > “Policy Type”/“Single Policy Format” the resultant XML output fails to include the \<PolicyID> and \<BasePolicyID>. 

If I create a policy that uses a pre-created policy from c:\windows\schemas\CodeIntegrity\ExamplePolicies -or- use the “Multiple Policy Format” the \<PolicyID> and \<BasePolicyID> are included in the XML resultant file.

![image](https://github.com/user-attachments/assets/9128d8f7-df0c-4957-8052-10803c27fefc)

![image](https://github.com/user-attachments/assets/bd5b52d9-2bd2-415a-b7af-197c4e6dec7e)

**Comment by jgeurten** [comment]
This is by design. Single format policies do not contain these elements

**Comment by PaulbBerg** [comment]
Would be helpful if this was noted somewhere, since the use in the new Intune Preview feature fails to apply to endpoints, There is no error to help the user understand why.

![image](https://github.com/user-attachments/assets/171f6189-a683-4692-b4ba-f40618bab876)

**Comment by jgeurten** [comment]
That's why I started the thread with the Intune team so they can fix the issue in the portal

**Comment by PaulbBerg** [comment]
[like]  Paul Bergson reacted to your message:
________________________________
