### ISSUE TITLE
File name feature issue

### ISSUE THREAD

**Issue by UB01609** [MicrosoftDocs/WDAC-Toolkit#421]
File name feature of WDAC wizard does not work when MinimumFileVersion is also selected. Utilizing newest WDAC Wizard version 2.5.0.1. When "File name:" is selected to create a Publisher allow or block rule and "Min. Version" is also selected the xml file allows all FileNames (FileName="*").

<img width="308" alt="{EF64DFF2-FE8C-4EA7-8093-8E9BD4B7F4CD}" src="https://github.com/user-attachments/assets/5e39157c-acf8-45f9-9ed4-ad04a45f33cb">

When only "File name:" is selected to create a Publisher allow or block rule and not "Min. Version" WDAC Wizard works as expected. This functionality works as expected for a file attribute rule.

<img width="308" alt="{F9A487E7-63E0-49EF-A22E-50D74877F5CB}" src="https://github.com/user-attachments/assets/d60ba233-b94f-4b48-812c-a6e667d90e69">

<img width="670" alt="{70B4F07B-CB32-4067-9B0E-37F801CDC1D6}" src="https://github.com/user-attachments/assets/48f337a7-98d7-4a7e-b31b-1ba168868aa1">

**Comment by jgeurten** [comment]
Great catch. Thank you
