### ISSUE TITLE
WDAC Wizard Crashes with Custom Values

### ISSUE THREAD

**Issue by UB01609** [MicrosoftDocs/WDAC-Toolkit#422]
Wizard Crashes when we try to “Use Custom Values” When creating version rule:

![image](https://github.com/user-attachments/assets/941f9303-59b5-4cff-a662-4b2def5f703b)

Recreate by:
1. creating an allow rule for any publisher
2. select "Use Custom Values
3. change version number
4. try to create rule (WDAC will crash)

**Comment by jgeurten** [comment]
This doesn't reproduce on the latest version. Can you please share the log file in %APPDATA%\temp\WDACWizard\temp

**Comment by UB01609** [comment]
I am now unable to reproduce the problem. Here is the Log file from last time the problem occurred. Looks like I am on a newer version now so the issue must have been fixed.
[Log_2024-11-15_T19-30-23.txt](https://github.com/user-attachments/files/17847641/Log_2024-11-15_T19-30-23.txt)

**Comment by jgeurten** [comment]
> I am now unable to reproduce the problem. Here is the Log file from last time the problem occurred. Looks like I am on a newer version now so the issue must have been fixed. [Log_2024-11-15_T19-30-23.txt](https://github.com/user-attachments/files/17847641/Log_2024-11-15_T19-30-23.txt)

Thanks for confirming!
