### ISSUE TITLE
I can't install the MSIX WDAC Wizard on my Win 10 Laptop

### ISSUE THREAD

**Issue by Obhiao1997** [MicrosoftDocs/WDAC-Toolkit#426]
I downloaded the WDAC MSIX file but it does not run on my laptop - asking for a program to choose from - which gives me a list of all browsers and notepad

What do I need to do to install the software on my laptop

**Comment by jgeurten** [comment]
@Obhiao1997 what version of Windows are you running? There are some per-version considerations for MSIX on Win10. 

See https://learn.microsoft.com/en-us/windows/msix/app-installer/install-update-app-installer and https://learn.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues

**Comment by Obhiao1997** [comment]
Hi please see

Windows 10 22H2
Feature Pack
1000.19060.1000.0
OS build 19045.5131

*Cheers!*

*Amrit*

**Comment by jgeurten** [comment]
Did you follow the troubleshooting steps:

https://learn.microsoft.com/en-us/windows/msix/app-installer/install-update-app-installer 
and 
https://learn.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues
