### ISSUE TITLE
Free-type of file/folder path results in empty value 

### ISSUE THREAD

**Issue by SeniorFeet** [MicrosoftDocs/WDAC-Toolkit#45]
When choosing a file/folder path rule, if you close the pop-up dialog box to choose the file/folder path, and then manually type the path to the folder/file (for example if referencing an SMB path that you don't necessarily have access to on your workstation). When you then click create rule, the value in the Reference File rule isn't added accurately to the policy signing rules list.

**Comment by jgeurten** [comment]
Addressing issue in PR #48
