### ISSUE TITLE
Editing Supplemental Policy converts it to a base policy

### ISSUE THREAD

**Issue by SeniorFeet** [MicrosoftDocs/WDAC-Toolkit#46]
When editing an existing supplemental policy, upon saving it converts the policy to a base policy.

**Comment by jgeurten** [comment]
This is also related to issue #44 and is addressed by PR #39. tl;dr the policy type was not being set upon initial import of the policy

**Comment by jgeurten** [comment]
The issue is observed on latest build 1.6.3.0. during supplemental policy edit and specifying at least one file rule.

**Comment by jgeurten** [comment]
Fixed in #67
