### ISSUE TITLE
Building Supplemental Policies Doesn't Appear to Work Properly

### ISSUE THREAD

**Issue by arekfurt** [MicrosoftDocs/WDAC-Toolkit#6]
Using the flow for creating a new Supplemental Policy appears to work fine until I hit the step of actually "building" it. An error then occurs. The only information provided is this:

> Setting additional parameters:
> 100% [progress bar]

> Error During Build
> Output location:
> Unable to locate

The same has occurred with three out of my three different attempts to build supplemental policies, trying different rule configurations for each. 

System Info:
Windows 10 Enterprise x64
v. 1903 (18362.836)

**Comment by jgeurten** [comment]
Hi @arekfurt, this issue has been addressed in v1.5.5. Please update to the latest version and let me know if the error persists. Thanks again!
