### ISSUE TITLE
Editing the DefaultWindows_Enforced.xml example policy with WDAC-Toolkit renders UMCI disabled in the resulting policy

### ISSUE THREAD

**Issue by adamcurrie1** [MicrosoftDocs/WDAC-Toolkit#61]
Edit the above example policy from a Win10 enterprise 20H2 using WDAC Policy Wizard 1.6.4.1.22.
Accept the defaults and continue through the wizard.
Ensure the policy rule for User Mode Code Integrity is switched to on (it is by default)
Complete the wizard with no additional rules
Deploy the resulting .CIP (I used GPO)
System Information confirms that Windows Defender Application Control User Mode Policy is off

Compiling the XML generated by the above process using PowerShell results in the same

Compiling the source example policy DefaultWindows_Enforced.xml untouched by WDAC Policy Wizard, deploying it with the same method, System Information confirms that Windows Defender Application Control User Mode Policy is Enforced.

**Comment by jgeurten** [comment]
Hi @adamcurrie1 can you please clarify the problem you are experiencing. Deploying the Windows works cip output by the Wizard results in User mode and kernel mode states = Audit Mode. Can you confirm this is what you are seeing?

Opening the MSIX, converting the DefaultWindows_Enforced.xml to cip and deploying the policy should also result in the above user mode and kernel mode states

**Comment by jgeurten** [comment]
Ah, the reason is that CIP (multiple policy format policies) cannot be deployed using GPO. Only single policy format policies can be deployed using GPO. 

Try copying the CIP to %System32%\CodeIntegrity\CIPolicies\Active and running refreshpolicy.exe (available from aka.ms/refreshpolicy)

**Comment by adamcurrie1** [comment]
I'll give that a go now, thanks
