### ISSUE TITLE
"Download the Installer" button broken due to ms-appinstaller protocol disabled

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/WDAC-Toolkit#62]
When I click the "Download the Installer" button and allow it to open App Installer, I get an App Installer window with the message "Cannot open app package".  The reason shown is "The ms-appinstaller protocol has been disabled.  Please ask the vendor to update the weblink.  For more information go to [aka.ms/ms-appinstaller-disabled](http://aka.ms/ms-appinstaller-disabled)."

The link goes to a docs page with this note at the top: 

> The ms-appinstaller scheme(protocol) has been disabled. This means App Installer will not be able to install an app directly from a web server and it will need to be downloaded first. Update the link on your website by removing 'ms-appinstaller:?source=' so that the MSIX package or.appinstaller file will be downloaded. This may increase the download size for some packages. The user can then install the package with App Installer.

**Comment by jgeurten** [comment]
The appinstaller protocol was disabled due to a spoofing vulnerability. I have removed the ms-appinstaller protocol in the HTML and replaced with hrefs. All links will now download the msix instead of the appinstaller file. 

#Fixed
