### ISSUE TITLE
WDAC - Remove item in WDAC policy wizard is not working while editing the policy

### ISSUE THREAD

**Issue by jgeurten** [MicrosoftDocs/WDAC-Toolkit#63]
Create a policy in WDAC policy wizard 
Select Single Policy Format 
Select Allow Microsoft Mode
Add custom Rule 
One Allow rule for a specific path
One Deny rule for a specific path
Next

Check the policy.xml file for the custom rules

Now, click on Home tab and go to Policy Editor
Open the above created policy file
Select your custom Deny rule and click Remove Item
Add different custom rule and click Next
Now, check the policy.xml file. It will have 3 custom rules including the one which you have removed. 
Remove Item functionality is not working while editing the policy.

Reported through ADO #38019991

**Comment by VinaySingal** [comment]
Hi Jordan,

We can label it as bug. As functionality of one component is not working correctly.

Regards
Vinay
