### ISSUE TITLE
The Wizard could sign your policy 

### ISSUE THREAD

**Issue by jgeurten** [MicrosoftDocs/WDAC-Toolkit#75]

**Comment by HotCakeX** [comment]
@lulMeow 
I have created a wiki post, only using official Microsoft guide and methods, to create a supported certificate and use it to sign WDAC policy files.

https://github.com/HotCakeX/Harden-Windows-Security/wiki/How-to-Create-and-Deploy-a-Signed-WDAC-Policy-(Windows-Defender-Application-Control)
